### ISSUE TITLE
一直显示“无法获取你的二维码,请检查你的网络连接”

### ISSUE THREAD

**Issue by zxm0591** [vufa/deepin-wine-wechat-arch#126]
我用的是manjaro xface 21.07
按以下指令安装
sudo pacman -S yay
yay -S deepin-wine-wechat
#同时也安装了QQ
yay -S deepin-wine-qq

电脑联网没有问题，QQ也能正常登录
只有微信，一直显示“无法获取你的二维码,请检查你的网络连接”

昨晚重新安装了 deepin-wine6-stable 问题依旧

**Comment by countstarlight** [comment]
参照 https://github.com/countstarlight/deepin-wine-wechat-arch/issues/122#issuecomment-868172238 试试，`deepin-wine-wechat` 还没有使用 `deepin-wine6`，安装 `deepin-wine6-stable` 不会有任何作用
