### ISSUE TITLE
安装了最新的版本后，别的窗口不能完全遮盖聊天框

### ISSUE THREAD

**Issue by imic07** [vufa/deepin-wine-wechat-arch#127]
系统：manjaro-kde latest
版本：aur/deepin-wine-wechat 3.3.0.115-1 (+31 1.35) (已安装)
问题如下，此时浏览器不能完全遮住微信边框：
![image](https://user-images.githubusercontent.com/16321067/126073333-66cb2ea9-b677-46c8-b073-ae3fb83b66e8.png)

另外来消息了，不能提醒

**Comment by countstarlight** [comment]
边框问题参照 [消除阴影边框](https://github.com/countstarlight/deepin-wine-wechat-arch#%E6%B6%88%E9%99%A4%E9%98%B4%E5%BD%B1%E8%BE%B9%E6%A1%86)，来消息了只有提示音，暂时不能解决
