### ISSUE TITLE
无法通过终端进入winecfg

### ISSUE THREAD

**Issue by nukemiko** [vufa/deepin-wine-wechat-arch#144]
安装了AUR里的deepin-wine-wechat包，在进行设置的时候输出如下：

```
> /opt/apps/com.qq.weixin.deepin/files/run.sh winecfg
/usr/bin/deepin-wine6-stable:行13: dpkg：未找到命令
/usr/bin/deepin-wine6-stable:行13: dpkg：未找到命令
wine: '/home/menacing/.deepinwine/Deepin-WeChat' is a 32-bit installation, it cannot support 64-bit applications.
```

**Comment by countstarlight** [comment]
换用 `deepin-wine5` 试试，测试发现 `deepin-wine6-stable` 还有不少问题，

从aur安装 `deepin-wine5`，并拷贝一份 `/opt/apps/com.qq.weixin.deepin/files/run.sh`，修改

```bash
export APPRUN_CMD="deepin-wine6-stable"
```

为

```bash
export APPRUN_CMD="deepin-wine5"
```

并删除本地安装目录：

```bash
rm -rf ~/.deepinwine/Deepin-WeChat
```

重启一下系统，用修改后的 `run.sh` 启动

**Comment by xuthus5** [comment]
换回 deepin-wine5 了，fedora下 deepin-wine6-stable 无法工作。在执行 helper 的 CallWeChat 时，_DeleteRegistry函数会被阻塞住
```
_DeleteRegistry()
{
    env WINEPREFIX="$WINEPREFIX" $WINE_CMD reg DELETE "$1" /f &> /dev/null
}
```

改为 命令执行 
```bash
$ deepin-wine6-stable reg DELETE "HKCU\\Software\\Tencent\\WeChat" "UpdateFailCnt" /f
wine version: 6.0
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0

wine: Call from 7B03A8AF to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 7B03A8AF (thread 00b8), starting debugger...
阻塞在这里了<-
```

**Comment by leonevilred** [comment]
> 换用 `deepin-wine5` 试试，测试发现 `deepin-wine6-stable` 还有不少问题，
> 
> 从aur安装 `deepin-wine5`，并拷贝一份 `/opt/apps/com.qq.weixin.deepin/files/run.sh`，修改
> 
> ```shell
> export APPRUN_CMD="deepin-wine6-stable"
> ```
> 
> 为
> 
> ```shell
> export APPRUN_CMD="deepin-wine5"
> ```
> 
> 并删除本地安装目录：
> 
> ```shell
> rm -rf ~/.deepinwine/Deepin-WeChat
> ```
> 
> 重启一下系统，用修改后的 `run.sh` 启动

大佬，有办法多开微信吗
