### ISSUE TITLE
无法找到run_v4.sh

### ISSUE THREAD

**Issue by gczgcz2015** [vufa/deepin-wine-wechat-arch#147]

**Comment by gczgcz2015** [comment]
➜  files ./run.sh
./run.sh:行53: /opt/deepinwine/tools/run_v4.sh: 没有那个文件或目录

环境信息：
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	20.2
Codename:	Nibia

**Comment by vufa** [comment]
最新版问题还存在吗？

**Comment by bigshans** [comment]
安装 deepin-wine-helper ， AUR 里的 deepin-wine-helper 和 deepin-wine-helper-full 都行，这些文件都在 deepin-wine-helper 里面。

**Comment by gczgcz2015** [comment]
> 最新版问题还存在吗？

![image](https://user-images.githubusercontent.com/15188637/147405203-b2b9f4ec-bb74-40f6-b41a-26a4c5d8bf94.png)
安装完成之后显示这个

**Comment by gczgcz2015** [comment]
> 安装 deepin-wine-helper ， AUR 里的 deepin-wine-helper 和 deepin-wine-helper-full 都行，这些文件都在 deepin-wine-helper 里面。

无法找到run_v4.sh好了 谢谢~

**Comment by yiufung** [comment]
安装 `deepin-wine-helper` 之后问题也解决了。

既然是需要的部件，是不是可以把这个加入 AUR 的 dependency 呢

**Comment by vufa** [comment]
不能复现这个问题，`deepin-wine-helper` 一直在 `deepin-wine-wechat` 的依赖里：https://github.com/vufa/deepin-wine-wechat-arch/blob/21a84e6959c59a8674439c9f0ed224ba131cc99c/.SRCINFO#L11

**Comment by yiufung** [comment]
回想起来，我原本就装了 `deepin-wine-helper` ，但文件夹里不包含 run_v3.sh 和 run_v4.sh ，文件最后修改日期是19年，是很久之前装的了。后来卸载又重装，拿到最新版后就好了。

看来是对 `deepin-wine-helper` 的版本有要求

**Comment by vufa** [comment]
已经修复：https://github.com/vufa/deepin-wine-wechat-arch/commit/a4f600626777dd9c68a649949f4a74ac852cbf9c
