### ISSUE TITLE
程序错误弹窗弹出

### ISSUE THREAD

**Issue by oatiz** [vufa/deepin-wine-wechat-arch#159]
## 问题描述
正常启动微信后，过一段时间(立即或几分钟之内)会弹出一个`程序错误`的弹窗，命令行启动结果与界面结果见下方

## 环境信息

|     程序包          |     版本          |
| ----------- | ----------- |
| wechatSetup.exe      |   3.4.0.38      |
| com.qq.weixin.deepin.deb   | 3.2.1.154deepin13_i386   |
| deepin-wine |  deepin-wine6-stable_6.0.0.17 |

## 期望结果

这个不影响基本的使用，点击关闭就好。但是在程序启动后有一个错误弹窗还是有一点不舒服，麻烦可以提供解决思路吗？

## 运行时结果
<details>
<summary>命令行启动结果</summary>
<p>

➤ /opt/apps/com.qq.weixin.deepin/files/run.sh
Run Deepin-WeChat 3.2.1.154deepin13 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid
total 144
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 14:50 c: -> ../drive_c
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com1 -> /dev/ttyS0
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com10 -> /dev/ttyS9
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com11 -> /dev/ttyS10
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com12 -> /dev/ttyS11
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com13 -> /dev/ttyS12
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com14 -> /dev/ttyS13
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com15 -> /dev/ttyS14
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com16 -> /dev/ttyS15
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com17 -> /dev/ttyS16
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com18 -> /dev/ttyS17
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com19 -> /dev/ttyS18
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com2 -> /dev/ttyS1
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com20 -> /dev/ttyS19
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com21 -> /dev/ttyS20
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com22 -> /dev/ttyS21
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com23 -> /dev/ttyS22
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com24 -> /dev/ttyS23
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com25 -> /dev/ttyS24
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com26 -> /dev/ttyS25
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com27 -> /dev/ttyS26
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com28 -> /dev/ttyS27
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com29 -> /dev/ttyS28
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com3 -> /dev/ttyS2
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com30 -> /dev/ttyS29
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com31 -> /dev/ttyS30
lrwxrwxrwx 1 lyraile lyraile 11 Nov  6 00:53 com32 -> /dev/ttyS31
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com4 -> /dev/ttyS3
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com5 -> /dev/ttyS4
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com6 -> /dev/ttyS5
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com7 -> /dev/ttyS6
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com8 -> /dev/ttyS7
lrwxrwxrwx 1 lyraile lyraile 10 Nov  6 00:53 com9 -> /dev/ttyS8
lrwxrwxrwx 1 lyraile lyraile  8 Nov  6 00:04 d:: -> /dev/sr0
lrwxrwxrwx 1 lyraile lyraile 13 Nov  6 14:50 y: -> /home/lyraile
lrwxrwxrwx 1 lyraile lyraile  1 Nov  6 14:50 z: -> /
CallApp Deepin-WeChat arg count 1: c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/lyraile/.deepinwine/Deepin-WeChat/drive_c/users/lyraile/Application Data/Tencent/WeChat/All Users/config/configEx.ini': No such file or directory
Sat Nov  6 02:50:58 PM CST 2021:kill WeChat.exe block
cat: /proc/11535/maps: No such file or directory
cat: /proc/11535/maps: No such file or directory
Sat Nov  6 02:50:58 PM CST 2021:tag bottle:
Sat Nov  6 02:50:58 PM CST 2021:active bottles:
/home/lyraile/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat

➤ [I] <MMKV.cpp:156::initialize> version v1.2.7 page size:4096
[I] <MMKV.cpp:198::initializeMMKV> root dir: C:\users\lyraile\Application Data\Tencent\WeChat\XPlugin\Info\
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
TcpLayer ThreadProc() run !!!
wine: Unhandled page fault on read access to 00000008 at address 12BAFCB3 (thread 0830), starting debugger...
</p>
</details> 

<details>
<summary>程序界面结果</summary>
<p>
<img src="https://user-images.githubusercontent.com/24953151/140601125-28a6b75b-9b97-495e-b2e2-37eb4969b4e9.png">
</p>
</details>

**Comment by vufa** [comment]
参照 https://github.com/vufa/deepin-wine-wechat-arch/issues/128#issuecomment-885525528

**Comment by oatiz** [comment]
@vufa 非常感谢

顺便问下，这个能在打包过程中给关掉码？如果可以的话，该怎么做呢？
