### ISSUE TITLE
deepin-wine6-stable_6.0.0.17-1_amd64.deb 404 无法安装此依赖

### ISSUE THREAD

**Issue by sushanlqs** [vufa/deepin-wine-wechat-arch#162]
三种方式无法安装，deepin-wine6-stable-amd64 等几个包，到AUR上面去看，都过期了，安装的时候都返回404，是不是跟这个有关系。请问还有什么解决方案。

**Comment by linhandev** [comment]
同问

**Comment by linhandev** [comment]
照着readme添加multilib，之后 sudo pacman -Sy 更新一下数据库试试

**Comment by 0xDkd** [comment]
我也有同样的问题，确实都过期了。

**Comment by sushanlqs** [comment]
@vufa  麻烦大神看下

**Comment by kakioff** [comment]
下载，仓库看的时候都是404

**Comment by vufa** [comment]
已经更新(用`deepin-wine5` 替代了 `deepin-wine6-stable`)，重新安装试试

**Comment by vufa** [comment]
已经更新(用`deepin-wine5` 替代了 `deepin-wine6-stable`)，重新安装试试

**Comment by kakioff** [comment]
> 已经更新(用`deepin-wine5` 替代了 `deepin-wine6-stable`)，重新安装试试

可以了，感谢。可以修复一下 `deepin-wine-qq-arch` 吗

**Comment by vufa** [comment]
@kakioff 修复了
