### ISSUE TITLE
3.4.0.38-3 设置打不开

### ISSUE THREAD

**Issue by soundlift** [vufa/deepin-wine-wechat-arch#165]
设置菜单闪一下就没了

系统托盘的设置可以打开

**Comment by Lozycs** [comment]
现在可以点完设置马上移到setting那里，不过不是正道方法。。

**Comment by xtellaris** [comment]
我也有同样的问题，改用tab键定位+Enter键也会发生同样的情况，点击左下角按钮，菜单弹出后立即消失

**Comment by xtellaris** [comment]
> 现在可以点完设置马上移到setting那里，不过不是正道方法。。

可以在状态栏图标右键进入微信设置

**Comment by xtellaris** [comment]
> 现在可以点完设置马上移到setting那里，不过不是正道方法。。

可以在状态栏图标右键进入微信设置

**Comment by pikakolendo02** [comment]
> 

tab过去后可以用空格键开菜单

**Comment by vufa** [comment]
v3.5.0.46-2 已经修复
