### ISSUE TITLE
WechatWin.dll文件缺失

### ISSUE THREAD

**Issue by xsxend** [vufa/deepin-wine-wechat-arch#166]
WechatWin.dll文件缺失

**Comment by xsxend** [comment]
基于X11的KDE

**Comment by vufa** [comment]
具体错误是什么

**Comment by soundlift** [comment]
![深度截图_plasmashell_20211119085310](https://user-images.githubusercontent.com/17586660/142520285-b68f89a6-8a21-4e3e-8ce6-cd449c356f73.png)
我的也冒出来这个问题了，今天刚出现的

**Comment by linguishi** [comment]
今天出现了这个！！！

**Comment by arklee** [comment]
是因为更新了libldap和lib32-libldap导致的，我之前开了testing源，更新了这两个包就出现了这个问题。暂时可以回退一下这两个包临时解决一下

**Comment by elegracer** [comment]
> 是因为更新了libldap和lib32-libldap导致的，我之前开了testing源，更新了这两个包就出现了这个问题。暂时可以回退一下这两个包临时解决一下

会滚到上一个minor版本，就ok了。
隔壁企业微信也是一样

**Comment by abcfy2** [comment]
> 是因为更新了libldap和lib32-libldap导致的，我之前开了testing源，更新了这两个包就出现了这个问题。暂时可以回退一下这两个包临时解决一下

应该是deepin-wine构建的时候使用了低版本的libldap构建的问题，发现使用arch自己的wine就没问题，但是arch自己的wine运行微信会有无法粘贴剪贴板的图到聊天窗的问题，有时候还会遇到输入光标消失，只能盲敲。

正在找有没有能用官方wine直接运行微信的方案……

**Comment by abcfy2** [comment]
用`WINEDEBUG=warn+all` 追踪了一下读取的类库问题，问题终于完美解决了，下载deepin的libldap以及相关依赖扔进`/usr/lib32/`就可以了。具体步骤如下：

下载 deepin 的 `libldap-2.4-2:i386` 和 `libsasl2-2:i386` 这两个包，具体下载地址:

- `libldap-2.4-2:i386`: https://community-packages.deepin.com/deepin/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb
- `libsasl2-2:i386`: https://community-packages.deepin.com/deepin/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb

下载之后解压这两个包的内容，参考命令如下:

```sh
ar -x 'libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb'
tar xvf data.tar.xz

ar -x 'libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb'
tar xvf data.tar.xz
```

然后将 `liblber-2.4.so.2`, `libldap-2.4.so.2`, `libldap_r-2.4.so.2`, `libsasl2.so.2` 这几个文件复制到`/usr/lib32`就行了:

```sh
sudo cp usr/lib/i386-linux-gnu/liblber-2.4.so.2 usr/lib/i386-linux-gnu/libldap-2.4.so.2 usr/lib/i386-linux-gnu/libldap_r-2.4.so.2 usr/lib/i386-linux-gnu/libsasl2.so.2 /usr/lib32/
```

问题解决，希望给遇到这个问题的朋友们参考。

**Comment by CyrusYip** [comment]
> 正在找有没有能用官方wine直接运行微信的方案……

@abcfy2 你可以试试 archlinuxcn 仓库的 `wine-wechat-setup` 和 `wine-for-wechat`，最新的 Arch Linux 能用。

**Comment by xsxend** [comment]
已经解决了我把libldap和lib32-libldap降级倒2.5.9可以正常运行了

**Comment by abcfy2** [comment]
> > 正在找有没有能用官方wine直接运行微信的方案……
> 
> @abcfy2 你可以试试 archlinuxcn 仓库的 `wine-wechat-setup` 和 `wine-for-wechat`，最新的 Arch Linux 能用。

那个试过了，问题依旧，看了下它的patch，其实对于wechat的问题 只是不疼不痒

**Comment by lilydjwg** [comment]
> 无法粘贴剪贴板的图到聊天窗的问题

以 BMP 格式复制就没有问题了。

```sh
clipboard_png2bmp () {
	xclip -selection clipboard -o -t image/png | convert - bmp:- | xclip -i -selection clipboard -t image/bmp
}
```

**Comment by abcfy2** [comment]
> > 无法粘贴剪贴板的图到聊天窗的问题
> 
> 以 BMP 格式复制就没有问题了。
> 
> ```shell
> clipboard_png2bmp () {
> 	xclip -selection clipboard -o -t image/png | convert - bmp:- | xclip -i -selection clipboard -t image/bmp
> }
> ```

原来如此。原版wine运行wechat在拖动窗体的时候还会有卡顿的情况，莫名闪烁等诸多小问题，还是暂时用deepin-wine运行好了，没这么多问题了

**Comment by abcfy2** [comment]
> > 无法粘贴剪贴板的图到聊天窗的问题
> 
> 以 BMP 格式复制就没有问题了。
> 
> ```shell
> clipboard_png2bmp () {
> 	xclip -selection clipboard -o -t image/png | convert - bmp:- | xclip -i -selection clipboard -t image/bmp
> }
> ```

顺便请教下，发现不管使用哪个wine，在KDE桌面下托盘都不会消息闪烁，只能听到新消息的音效，这个是否有解决方案呢？谢谢

**Comment by lilydjwg** [comment]
> 顺便请教下，发现不管使用哪个wine，在KDE桌面下托盘都不会消息闪烁，只能听到新消息的音效，这个是否有解决方案呢？谢谢

我不用 KDE。我这里 wine 的托盘甚至是个单独的窗口（而不是进系统托盘）。

不闪好啊。我讨厌它一直闪啊闪的，干扰太严重。

**Comment by muyuuuu** [comment]
我以为是啥软件 bug 呢，就卸载了 wechat 重装，好气，早知道先来看 issue 了。

**Comment by arklee** [comment]
> 我以为是啥软件 bug 呢，就卸载了 wechat 重装，好气，早知道先来看 issue 了。
> 
> 降级包大家都会，多问一句，是如何根据报错判断出哪个包导致的问题呢？我也想学。

没啥判断方法。就是Syu更新完发现微信启动不了了，然后看了下日志更新了哪些包。这就是每天都滚的好处了，一旦出问题可以快速定位到出问题的包。

**Comment by vufa** [comment]
> 用`WINEDEBUG=warn+all` 追踪了一下读取的类库问题，问题终于完美解决了，下载deepin的libldap以及相关依赖扔进`/usr/lib32/`就可以了。具体步骤如下：
> 
> 下载 deepin 的 `libldap-2.4-2:i386` 和 `libsasl2-2:i386` 这两个包，具体下载地址:
> 
> * `libldap-2.4-2:i386`: https://community-packages.deepin.com/deepin/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb
> * `libsasl2-2:i386`: https://community-packages.deepin.com/deepin/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb
> 
> 下载之后解压这两个包的内容，参考命令如下:
> 
> ```shell
> ar -x 'libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb'
> tar xvf data.tar.xz
> 
> ar -x 'libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb'
> tar xvf data.tar.xz
> ```
> 
> 然后将 `liblber-2.4.so.2`, `libldap-2.4.so.2`, `libldap_r-2.4.so.2`, `libsasl2.so.2` 这几个文件复制到`/usr/lib32`就行了:
> 
> ```shell
> sudo cp usr/lib/i386-linux-gnu/liblber-2.4.so.2 usr/lib/i386-linux-gnu/libldap-2.4.so.2 usr/lib/i386-linux-gnu/libldap_r-2.4.so.2 usr/lib/i386-linux-gnu/libsasl2.so.2 /usr/lib32/
> ```
> 
> 问题解决，希望给遇到这个问题的朋友们参考。

感谢帮助，已经加入打包：https://github.com/vufa/deepin-wine-wechat-arch/commit/105427a648d2d3b63a7bf7e0ad342eae2f042f48

**Comment by Crany-web** [comment]
> 用`WINEDEBUG=warn+all` 追踪了一下读取的类库问题，问题终于完美解决了，下载deepin的libldap以及相关依赖扔进`/usr/lib32/`就可以了。具体步骤如下：
> 
> 下载 deepin 的 `libldap-2.4-2:i386` 和 `libsasl2-2:i386` 这两个包，具体下载地址:
> 
> * `libldap-2.4-2:i386`: https://community-packages.deepin.com/deepin/pool/main/o/openldap/libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb
> * `libsasl2-2:i386`: https://community-packages.deepin.com/deepin/pool/main/c/cyrus-sasl2/libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb
> 
> 下载之后解压这两个包的内容，参考命令如下:
> 
> ```shell
> ar -x 'libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb'
> tar xvf data.tar.xz
> 
> ar -x 'libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb'
> tar xvf data.tar.xz
> ```
> 
> 然后将 `liblber-2.4.so.2`, `libldap-2.4.so.2`, `libldap_r-2.4.so.2`, `libsasl2.so.2` 这几个文件复制到`/usr/lib32`就行了:
> 
> ```shell
> sudo cp usr/lib/i386-linux-gnu/liblber-2.4.so.2 usr/lib/i386-linux-gnu/libldap-2.4.so.2 usr/lib/i386-linux-gnu/libldap_r-2.4.so.2 usr/lib/i386-linux-gnu/libsasl2.so.2 /usr/lib32/
> ```
> 
> 问题解决，希望给遇到这个问题的朋友们参考。

libsasl2-2:i386疑似被删除，访问链接显示404
