### ISSUE TITLE
Manjaro KDE：deepin-wine-wechat-3.4.0.38-4安装失败

### ISSUE THREAD

**Issue by liyuj** [vufa/deepin-wine-wechat-arch#169]
软件包 (1) deepin-wine-wechat-3.4.0.38-4

全部安装大小：  189.00 MiB

:: 进行安装吗？ [Y/n] 
(1/1) 正在检查密钥环里的密钥                                                                     [#########################################################] 100%
(1/1) 正在检查软件包完整性                                                                       [#########################################################] 100%
(1/1) 正在加载软件包文件                                                                         [#########################################################] 100%
(1/1) 正在检查文件冲突                                                                           [#########################################################] 100%
错误：无法提交处理 (有冲突的文件)
deepin-wine-wechat: 文件系统中存在 /usr/lib32/liblber-2.4.so.2 （由 lib32-libldap 所有）
deepin-wine-wechat: 文件系统中存在 /usr/lib32/libldap-2.4.so.2 （由 lib32-libldap 所有）
deepin-wine-wechat: 文件系统中存在 /usr/lib32/libldap_r-2.4.so.2 （由 lib32-libldap 所有）
发生错误，没有软件包被更新。
 -> exit status 1

**Comment by vufa** [comment]
啊这 我忘记了这几个库是其他依赖的😥

**Comment by gaoyu19920914** [comment]
+1 遇到了同样的问题。

conflicting files:
- deepin-wine-wechat: /usr/lib32/liblber-2.4.so.2 already exists in filesystem (owned by lib32-libldap)
- deepin-wine-wechat: /usr/lib32/libldap-2.4.so.2 already exists in filesystem (owned by lib32-libldap)
- deepin-wine-wechat: /usr/lib32/libldap_r-2.4.so.2 already exists in filesystem (owned by lib32-libldap)

**Comment by liyuj** [comment]
暂时回退上一版本解决问题。

git checkout -b test 803f2c53fa0b3fa3959f12849216fe86d5955551

makepkg -si

在 2021/11/25 16:55, Vufa 写道:

**Comment by Delta-in-hub** [comment]
same issue

**Comment by vufa** [comment]
已经修复：https://github.com/vufa/deepin-wine-wechat-arch/commit/14898a3f2238d2f8beaf9d3aae3b835015b7e2b9

**Comment by xiangsheng** [comment]
仍然无法运行，首次运行时，一个疑似微信安装窗口一闪而过，然后就没有任何动静了

**Comment by gaoyu19920914** [comment]
> 仍然无法运行，首次运行时，一个疑似微信安装窗口一闪而过，然后就卡在这里，微信安装并没有发生。
> 
> 似乎用deepin5的版本都有这样的问题。

我这没问题。安装窗口会闪两三次，但是最后就安装好了。
