### ISSUE TITLE
功能请求：更新时保留原来的 dpi 配置

### ISSUE THREAD

**Issue by CyrusYip** [vufa/deepin-wine-wechat-arch#173]
每次更新完之后都要重新设置 dpi，有没有办法可以保存呢？

**Comment by choyy** [comment]
我也想问有没有简单的解决办法

**Comment by abcfy2** [comment]
在`/etc/environment`文件(全局配置，对所有用户生效，修改需要`root`权限)或`~/.pam_environment`(没有可以创建一个，无需root权限，仅对当前用户生效)添加一行:

```ini
DEEPIN_WINE_SCALE=1.25
```

即可，这个值具体设置多少可以参考Windows10的那个显示设置(125%, 150%, 200%等等)。修改完毕之后重启系统即可生效

**Comment by CyrusYip** [comment]
我把 `DEEPIN_WINE_SCALE=1.5` 写入 `~/.pam_environment`，执行 `/opt/apps/com.qq.weixin.deepin/files/run.sh winecfg` 将 dpi 改为 96，然后重启。打开微信发现没有缩放为 150%。

**Comment by abcfy2** [comment]
`~/.pam_environment` 和 `/etc/environment` 应该都是系统启动的时候才会加载，你在`env | grep DEEPIN_WINE_SCALE`检查下有没有这个环境变量，没有重启系统之后看看有没有。

**Comment by CyrusYip** [comment]
我重启过了，有这个环境变量。

```
❯ env | grep DEEPIN_WINE_SCALE
DEEPIN_WINE_SCALE=1.5
```

**Comment by abcfy2** [comment]
这个环境变量只对deepin-wine有效，检查你的`/opt/apps/com.qq.weixin.deepin/files/run.sh`使用的`APPRUN_CMD`是不是`deepin-wine6-stable`或者`deepin-wine5`?

如果是的话应该没问题。你也可以试试删除wine容器路径重新初始化 `rm -fr ~/.deepinwine/Deepin-WeChat/`

**Comment by choyy** [comment]
@vufa 建议把这个方法加入README

**Comment by CyrusYip** [comment]
@abcfy2 我的 `/opt/apps/com.qq.weixin.deepin/files/run.sh` 里面的是 `deepin-wine5`。

```
export APPRUN_CMD="deepin-wine5"
```

删除容器之后重新初始化，现在 dpi 变成 150% 了，谢谢！

**Comment by WWWzq-01** [comment]
> @abcfy2 我的 `/opt/apps/com.qq.weixin.deepin/files/run.sh` 里面的是 `deepin-wine5`。
> 
> ```
> export APPRUN_CMD="deepin-wine5"
> ```
> 
> 删除容器之后重新初始化，现在 dpi 变成 150% 了，谢谢！

我想问问重新初始化就是重新安装嘛

**Comment by CyrusYip** [comment]
@WWWzq-01 是执行 `rm -fr ~/.deepinwine/Deepin-WeChat/` 之后再打开微信。

**Comment by 276562578** [comment]
我的run.sh是
```bash
export APPRUN_CMD="deepin-wine6-stable"
```
但只有winecfg能调节，删除`rm -fr ~/.deepinwine/Deepin-WeChat/ `之后重新安装无效
