### ISSUE TITLE
无法安装和更新最新版本？

### ISSUE THREAD

**Issue by night-every** [vufa/deepin-wine-wechat-arch#174]
yay -S deepin-wine-wechat

:: 正在检查冲突...
:: 正在检查内部冲突...
[Aur:1]  deepin-wine-wechat-3.4.0.54-1

:: (1/1) Downloaded PKGBUILD: deepin-wine-wechat
  1 deepin-wine-wechat                       (构建文件已存在)
==> 显示哪些差异？
==> [N]没有 [A]全部 [Ab]中止 [I]已安装 [No]未安装 或 (1 2 3, 1-3, ^4)
==> N
:: (1/1) 正在解析 SRCINFO: deepin-wine-wechat
==> 正在创建软件包：deepin-wine-wechat 3.4.0.54-1 (Mon 06 Dec 2021 12:53:45 AM +08)
==> 获取源代码...
  -> 正在下载 com.qq.weixin.deepin_3.2.1.154deepin14_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:00 --:--:--     0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to com-store-packages.uniontech.com:443 
==> 错误： 无法下载 https://com-store-packages.uniontech.com/appstore/pool/appstore/c/com.qq.weixin.deepin/com.qq.weixin.deepin_3.2.1.154deepin14_i386.deb
    正在放弃...
 -> 下载源文件时出错: deepin-wine-wechat 
	 context: exit status 1 
	 

==> 正在创建软件包：deepin-wine-wechat 3.4.0.54-1 (Mon 06 Dec 2021 12:54:50 AM +08)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 正在下载 com.qq.weixin.deepin_3.2.1.154deepin14_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   145  100   145    0     0     94      0  0:00:01  0:00:01 --:--:--    95
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
100  159M  100  159M    0     0  9921k      0  0:00:16  0:00:16 --:--:-- 12.5M
  -> 正在下载 WeChatSetup-3.4.0.54.exe...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  155M  100  155M    0     0  12.4M      0  0:00:12  0:00:12 --:--:-- 12.2M
  -> 正在下载 libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  230k  100  230k    0     0   110k      0  0:00:02  0:00:02 --:--:--  110k
  -> 正在下载 libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  107k  100  107k    0     0  25142      0  0:00:04  0:00:04 --:--:-- 25145
  -> 找到 run.sh
  -> 找到 reg.patch
==> 正在验证 source 文件，使用md5sums...
    com.qq.weixin.deepin_3.2.1.154deepin14_i386.deb ... 通过
    WeChatSetup-3.4.0.54.exe ... 失败
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... 通过
    libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb ... 通过
    run.sh ... 通过
    reg.patch ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！
 -> 生成时出错: deepin-wine-wechat

**Comment by RisaKirisu** [comment]
我遇到了同样的错误，以前用yay安装过deepin-wechat，但是无法使用中文输入法，卸载了。刚才安装最新的版本，选择cleanBuild发生同样错误。

**Comment by qxqzx3489** [comment]
将pkgbuild里面的md5sums 都改为SKIP

**Comment by night-every** [comment]
md5sums=('SKIP'	
	  'SKIP'
	   'SKIP'
            'SKIP'
	    'SKIP'
            'SKIP')

**Comment by night-every** [comment]
谢谢

**Comment by vufa** [comment]
感谢提醒，已经更新：https://github.com/vufa/deepin-wine-wechat-arch/commit/b17c03238bffe9e82b26a684b2c6373b24d45d67
