### ISSUE TITLE
哈希值有误

### ISSUE THREAD

**Issue by black-desk** [vufa/deepin-wine-wechat-arch#177]
![image](https://user-images.githubusercontent.com/29726878/145665124-c6e8fa2c-5e19-47e9-be78-83d4da39fbad.png)
![image](https://user-images.githubusercontent.com/29726878/145665138-ac9cd7ed-baf4-4cd4-bfe9-3d29cc72525a.png)

**Comment by black-desk** [comment]
https://github.com/vufa/deepin-wine-wechat-arch/commit/b17c03238bffe9e82b26a684b2c6373b24d45d67#diff-da6e50bd048b01fce3a730750d3f6fc41a3ddbe8c2e8ac6e4f7d4ef09fc1e124R29

看来你改错东西了?

**Comment by vufa** [comment]
应该没有问题，[GitHub Action构建](https://github.com/vufa/deepin-wine-wechat-arch/runs/4486105934?check_suite_focus=true)没有出错

**Comment by black-desk** [comment]
诶 我本地构建出错了诶 怪

**Comment by black-desk** [comment]
![image](https://user-images.githubusercontent.com/29726878/145665395-c7a1addc-1921-49b9-8367-528b212988c5.png)

**Comment by black-desk** [comment]
我已经删了缓存了 会不会腾讯动了什么东西

**Comment by night-every** [comment]
`md5sums=('SKIP'
           'SKIP'
         'SKIP'
         'SKIP'
         'SKIP'
         'SKIP')`

在pkgbuild里的md5sums全部改成SKIP就可以正常升级了。

**Comment by black-desk** [comment]
> `md5sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')`
> 
> 在pkgbuild里的md5sums全部改成SKIP就可以正常升级了。

我知道怎么处理 但是就很怪啊

**Comment by Apricot1024** [comment]
我也遇到了 这个问题，还不是第一次，莫名奇妙的问题

**Comment by black-desk** [comment]
你们说会不会是腾讯对于不同地方的人会下发不一样的二进制啊

**Comment by linhandev** [comment]
```shell
yay --mflags --skipinteg deepin-wine-wechat
```
可以跳过哈希校验

**Comment by its404** [comment]
我之前也遇到过类似的问题，https://github.com/vufa/deepin-wine-wechat-arch/issues/135#issuecomment-899002706 
最后用安装包安装成功了。

**Comment by vufa** [comment]
已经更新：https://github.com/vufa/deepin-wine-wechat-arch/commit/ec863a77c14725f7cb7a77b252c13d4b1b09c657
