### ISSUE TITLE
系统及微信更新后无法正常运行

### ISSUE THREAD

**Issue by RadxaYuntian** [vufa/deepin-wine-wechat-arch#179]
昨天要装个软件就yay -Syu了一下，结果3.4.5无法运行。表现就是登录窗口显示但没有响应（鼠标移上去没有光标显示），然后过一段时间弹出错误报告：
![image](https://user-images.githubusercontent.com/95260730/146294089-4e7bfeac-a379-4dbb-90d9-00bfeece1036.png)

<details>
<summary>$ /opt/apps/com.qq.weixin.deepin/files/run.sh</summary>

Run Deepin-WeChat 3.2.1.154deepin14 c:/Program Files/Tencent/WeChat/WeChat.exe
run Deepin-WeChat progress pid 
total 148
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:41 c: -> ../drive_c
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com1 -> /dev/ttyS0
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com10 -> /dev/ttyS9
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com11 -> /dev/ttyS10
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com12 -> /dev/ttyS11
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com13 -> /dev/ttyS12
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com14 -> /dev/ttyS13
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com15 -> /dev/ttyS14
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com16 -> /dev/ttyS15
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com17 -> /dev/ttyS16
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com18 -> /dev/ttyS17
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com19 -> /dev/ttyS18
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com2 -> /dev/ttyS1
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com20 -> /dev/ttyS19
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com21 -> /dev/ttyS20
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com22 -> /dev/ttyS21
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com23 -> /dev/ttyS22
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com24 -> /dev/ttyS23
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com25 -> /dev/ttyS24
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com26 -> /dev/ttyS25
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com27 -> /dev/ttyS26
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com28 -> /dev/ttyS27
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com29 -> /dev/ttyS28
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com3 -> /dev/ttyS2
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com30 -> /dev/ttyS29
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com31 -> /dev/ttyS30
lrwxrwxrwx 1 yuntian yuntian 11 12月 16 09:40 com32 -> /dev/ttyS31
lrwxrwxrwx 1 yuntian yuntian 12 12月 16 09:40 com33 -> /dev/ttyUSB0
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com4 -> /dev/ttyS3
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com5 -> /dev/ttyS4
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com6 -> /dev/ttyS5
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com7 -> /dev/ttyS6
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com8 -> /dev/ttyS7
lrwxrwxrwx 1 yuntian yuntian 10 12月 16 09:40 com9 -> /dev/ttyS8
lrwxrwxrwx 1 yuntian yuntian  8 12月 16 09:40 d:: -> /dev/sr0
lrwxrwxrwx 1 yuntian yuntian 13 12月 16 09:41 y: -> /home/yuntian
lrwxrwxrwx 1 yuntian yuntian  1 12月 16 09:41 z: -> /
CallApp Deepin-WeChat arg count 1: c:/Program Files/Tencent/WeChat/WeChat.exe
Disable auto update
rm: cannot remove '/home/yuntian/.deepinwine/Deepin-WeChat/drive_c/users/yuntian/Application Data/Tencent/WeChat/All Users/config/configEx.ini': No such file or directory
2021年 12月 16日 星期四 09:41:58 CST:kill WeChat.exe block
cat: /proc/1411/maps: Permission denied
cat: /proc/1411/maps: Permission denied
cat: /proc/17236/maps: No such file or directory
cat: /proc/17236/maps: No such file or directory
2021年 12月 16日 星期四 09:41:58 CST:tag bottle: 
2021年 12月 16日 星期四 09:41:58 CST:active bottles: 
/home/yuntian/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
[yuntian@Yuntian ~]$ wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
wine: Read access denied for device L"\\??\\Z:\\", FS volume label and serial are not available.
[I] <MMKV.cpp:156::initialize> version v1.2.7 page size:4096
[I] <MMKV.cpp:198::initializeMMKV> root dir: C:\users\yuntian\Application Data\Tencent\WeChat\XPlugin\Info\
TcpLayer ThreadProc() run !!!
</details>

使用GitHub release里面3.4.5和3.4.0均无效。已尝试删除用户文件夹。

**Comment by RadxaYuntian** [comment]
更新后同时设置了一下`~/.pam_environment`弄DPI。删了后自己折腾了下winecfg里的dpi似乎能打开程序了，但扫码登录一直进不去……

**Comment by georgebwang** [comment]
同样问题，昨天做了一次system update今天开机之后就打开不了微信了，显示相同界面。已尝试downgrade安装旧版本，并无改善。
![image](https://user-images.githubusercontent.com/60869280/146318854-b2cc9dd7-5213-4bf6-accc-0960b779ddd1.png)

**Comment by faonecze** [comment]
昨晚升级后关机,今天用发现打不开了.重新构建后正常...不知道重启后还会不会正常...

**Comment by georgebwang** [comment]
> 昨天要装个软件就yay -Syu了一下，结果3.4.5无法运行。表现就是登录窗口显示但没有响应（鼠标移上去没有光标显示），然后过一段时间弹出错误报告： ![image](https://user-images.githubusercontent.com/95260730/146294089-4e7bfeac-a379-4dbb-90d9-00bfeece1036.png)
> 
> $ /opt/apps/com.qq.weixin.deepin/files/run.sh
> 使用GitHub release里面3.4.5和3.4.0均无效。已尝试删除用户文件夹。

请问题主现在解决了吗？我这里还是不行。也尝试删除文件夹+完全重装了。

**Comment by RadxaYuntian** [comment]
@georgebwang Nope still stucked at Loggin In screen.

**Comment by glide-the** [comment]
同样出现上面的那种情况，但是之前版本应该怎么下载。。

**Comment by georgebwang** [comment]
前天重装了电脑，发现这个问题应该和NVIDIA驱动有关， 我先装NVIDIA驱动再装微信就会出现以上问题， 而先装微信再装NVIDIA驱动就可以正常使用了。

**Comment by RadxaYuntian** [comment]
@glide-the https://github.com/vufa/deepin-wine-wechat-arch/releases https://github.com/vufa/deepin-wine-wechat-arch#%E6%9C%AC%E5%9C%B0%E6%89%93%E5%8C%85%E5%AE%89%E8%A3%85

@georgebwang 我这边是Ryzen 5600G，没有Nvidia驱动。回头重装个Manjaro试试

**Comment by glide-the** [comment]
> @glide-the [https://github.com/vufa/deepin-wine-wechat-arch/releases ](https://github.com/vufa/deepin-wine-wechat-arch/releases) [https://github.com/vufa/deepin-wine-wechat-arch#%E6%9C%AC%E5% 9C%B0%E6%89%93%E5%8C%85%E5%AE%89%E8%A3%85](https://github.com/vufa/deepin-wine-wechat-arch#%E6%9C%AC%E5%9C%B0%E6%89%93%E5%8C%85%E5%AE%89%E8%A3%85)
> 
> @georgebwang我这个是锐龙5600G，没有Nvidia驱动。
哦豁，这bug是真的吊，我还准备把我笔记本上的系统同步到台式机，看下是不是什么包的打包出错了，现在，得了这个根本解决不了
还有就是我台式机的显示，在我备份之后，如果不装官方的Nvidia驱动，就会启动打不开Xserver服务，我严重怀疑是nvidia-utils这个包的bug。。。

**Comment by glide-the** [comment]
> > @glide-the  [https://github.com/vufa/deepin-wine-wechat-arch/releases ](https://github.com/vufa/deepin-wine-wechat-arch/releases) [https://github.com/vufa/deepin-wine-wechat-arch#%E6%9C%AC%E5% 9C%B0%E6%89%93%E5%8C%85%E5%AE%89%E8%A3%85](https://github.com/vufa/deepin-wine-wechat-arch#%E6%9C%AC%E5%9C%B0%E6%89%93%E5%8C%85%E5%AE%89%E8%A3%85)
> > @georgebwang00我这个是锐龙560G，没有Nvidia驱动。
> > 哦，这bug是吊，我准备我笔记本上的系统同步到观看把机，下是不是什么包的打包出错了，现在，这个根本解决不了
> > 还有就是我拍摄机的显示，在我备份之后，如果不安装官方的Nvidia驱动，就会启动打不开Xserver服务，我严重怀疑是nvidia-utils包的bug。。。

笔记本
amd h4800cpu
AMD的显卡，默认amdgpu驱动，
微信正常使用
台式机 
intel cpu
NvidiaGTX1060 装了官网驱动
微信更新后不正常

**Comment by vufa** [comment]
安装 `lib32-nvidia-utils` 试试：
```bash
sudo pacman -S lib32-nvidia-utils
```

**Comment by glide-the** [comment]
> 安装 `lib32-nvidia-utils` 试试：
> 
> ```shell
> sudo pacman -S lib32-nvidia-utils
> ```
lib32-nvidia-utils这个包，
 官网的nvidia驱动内置了这个模块，不能同时安装，不然只能第一次安装后可以打开，重启之后，只能看到黑乎乎的窗口。。

**Comment by Reflyer823** [comment]
> 安装 `lib32-nvidia-utils` 试试：
> 
> ```shell
> sudo pacman -S lib32-nvidia-utils
> ```

感谢！我也是遇到楼上一样的问题，安装这个包以后就解决了

**Comment by KYatoo** [comment]
> > 安装 `lib32-nvidia-utils` 试试：
> > ```shell
> > sudo pacman -S lib32-nvidia-utils
> > ```
> 
> lib32-nvidia-utils这个包， 官网的nvidia驱动内置了这个模块，不能同时安装，不然只能第一次安装后可以打开，重启之后，只能看到黑乎乎的窗口。。

我也是，装上之后直接开不开机了。。。进不去图形界面

**Comment by RadxaYuntian** [comment]
3.5.0.46可以登录
