### ISSUE TITLE
看不了图片也发不了图片

### ISSUE THREAD

**Issue by Jokin613** [vufa/deepin-wine-wechat-arch#185]
看图的时候是这样，一直是白的
![1642479139](https://user-images.githubusercontent.com/27663488/149869741-16522e30-018f-4386-8fb4-7e142c7d9b62.png)

给别人发图的时候发不出去

**Comment by vufa** [comment]
v3.5.0.46-2 还存在这个问题吗

**Comment by Jokin613** [comment]
> v3.5.0.46-2 还存在这个问题吗

不清楚，之前用的f2fs后来重装ext4就可以了
