### ISSUE TITLE
manjaro kde，点击微信左下角的更多时，界面刚弹出来就消失

### ISSUE THREAD

**Issue by Sakura-gh** [vufa/deepin-wine-wechat-arch#187]
这样似乎就没法进入设置界面了...，而且多点击几次后出现闪退
<img width="339" alt="image" src="https://user-images.githubusercontent.com/50900131/150729257-abf18b38-a8a3-43bc-b642-62e4f05b5ecb.png">

**Comment by vufa** [comment]
参照 https://github.com/vufa/deepin-wine-wechat-arch/issues/165#issuecomment-979784750

**Comment by Sakura-gh** [comment]
> 参照 [#165 (comment)](https://github.com/vufa/deepin-wine-wechat-arch/issues/165#issuecomment-979784750)

thanks~
