### ISSUE TITLE
AUR更新v3.5.0.46-2後出現黑框

### ISSUE THREAD

**Issue by PaulHJB** [vufa/deepin-wine-wechat-arch#191]
![1](https://user-images.githubusercontent.com/99173429/152756451-41965d3b-ed25-49e2-980b-cd80e8e46677.png)
如圖，openbox，lxqt1.0

**Comment by vufa** [comment]
可以暂时降级到 [v3.5.0.46-1](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.5.0.46-1)，参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by PaulHJB** [comment]
> 可以暂时降级到 [v3.5.0.46-1](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.5.0.46-1)，参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

降級後，問題解決。謝謝

**Comment by PaulHJB** [comment]
已解決
