### ISSUE TITLE
建议安装完成后出现中文字符、阴影边框等问题，手动跑一边run.sh

### ISSUE THREAD

**Issue by biuniun** [vufa/deepin-wine-wechat-arch#194]
不太确定是不是deepin-wine6的适配问题，正常添加环境变量无法使微信运行在deepin-wine6中，需手动重新运行run.sh才能回复正常。

未运行之前的状态：
中文字符无法显示（系统语言英文）
阴影边框

手动运行run.sh后所有问题消失。考虑到前面所处出现的问题都是使用native wine所常见的，参考解决问题的途径，怀疑是没有成功自动切换wine。

同时：
如果按照老版本readme中所写，在运行的脚本是传入‘-d'，新的run.sh会报错，怀疑是因此造成的切换失败

**Comment by vufa** [comment]
* 参照 [README](https://github.com/vufa/deepin-wine-wechat-arch#%E5%88%87%E6%8D%A2%E5%88%B0-deepin-wine)，新版 `deepin-wine-wechat` 默认使用 `deepin-wine6-stable`/`deepin-wine5`，不再需要进行任何切换操作，`run.sh` 本身也不再支持任何切换操作
* 更新后没有正常调用 `deepin-wine6-stable` 可能是由系统中残留的 `deepin-wine5`进程导致，尝试重启系统
* 中文字体不能正常显示参照 [中文字体显示为方框/显示模糊](https://github.com/vufa/deepin-wine-wechat-arch#%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E6%98%BE%E7%A4%BA%E4%B8%BA%E6%96%B9%E6%A1%86%E6%98%BE%E7%A4%BA%E6%A8%A1%E7%B3%8A) 和 https://github.com/vufa/deepin-wine-wechat-arch/issues/186#issuecomment-1029892154
