### ISSUE TITLE
接收到的文件右击在文件夹中显示会打开浏览器

### ISSUE THREAD

**Issue by imic07** [vufa/deepin-wine-wechat-arch#195]
升级到3.5.0.46-2后 打开文件有问题：
![image](https://user-images.githubusercontent.com/16321067/153545266-5b931aad-3be9-409e-9b9e-8120913174c5.png)

![image](https://user-images.githubusercontent.com/16321067/153545107-d7d5d57b-a7ce-4120-a5a8-e9a1619164ec.png)

**Comment by JYInMyHeart** [comment]
我也遇到这个问题了！

**Comment by wxqwinner** [comment]
`sudo vim /bin/dde-file-manager`
然后根据自己用的文件管理器添加内容，比如我的
```
#!/bin/bash
nautilus --select "$2"
```

**Comment by vufa** [comment]
@wxqwinner 感谢帮助，目前找不到更好的方法，dolphin的`/bin/dde-file-manager`为：
```bash
#!/bin/sh
dolphin --select "$2"
```
需要赋予执行权限：
```bash
sudo chmod +x /bin/dde-file-manager
```
