### ISSUE TITLE
小程序公众号还是打不开

### ISSUE THREAD

**Issue by imic07** [vufa/deepin-wine-wechat-arch#196]
升级到3.5.0.46-2后 还是打不开小程序等。
![image](https://user-images.githubusercontent.com/16321067/153545868-e3326aec-e806-4bce-b04b-88d1f83fcbfa.png)

打开后也不能关闭了，只能退出进程：

![image](https://user-images.githubusercontent.com/16321067/153545551-ebcb6d20-98e5-4cf0-b852-35b3fbb5fd0f.png)

**Comment by vufa** [comment]
参照 https://github.com/vufa/deepin-wine-wechat-arch/issues/186#issuecomment-1029892154 试试

**Comment by imic07** [comment]
yay -S noto-fonts-sc

安装noto-fonts-cjk之后微信报错的问题解决了，但是打开小程序字体乱码，这个还没找到好办法

![image](https://user-images.githubusercontent.com/16321067/154017287-1ad66de4-9ff9-4751-afd4-855354da393e.png)

**Comment by likfees** [comment]
我将 `Windows/Fonts/` 下的所有.ttf,.ttc 文件复制到 `$HOME/.deepinwine/Deepin-WeChat/drive_c/windows/Fonts` 小程序字体都可以正常显示了
