### ISSUE TITLE
md5 校验不通过

### ISSUE THREAD

**Issue by hypghzy** [vufa/deepin-wine-wechat-arch#197]
==> 正在验证 source 文件，使用md5sums...
    com.qq.weixin.deepin_3.4.0.38deepin4_i386.deb ... 失败
    WeChatSetup-3.5.0.46.exe ... 通过
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... 通过
    libsasl2-2_2.1.27+dfsg-1+deb10u1_i386.deb ... 通过
    run.sh ... 通过

有个包md5 校验不通过的样子

**Comment by vufa** [comment]
感谢帮助，已经更新

**Comment by hypghzy** [comment]
> 感谢帮助，已经更新

感谢更新，已经成功安装上了。
开发组辛苦啦～
