### ISSUE TITLE
新版的deepin-wine-wechat依旧还是有阴影，按照旧方案更改无用

### ISSUE THREAD

**Issue by Apple-QAQ** [vufa/deepin-wine-wechat-arch#200]
![image](https://user-images.githubusercontent.com/88485487/154468546-6abbcc5d-899b-4ba9-88d7-b26b36a49617.png)

**Comment by vufa** [comment]
应该是 `deepin-wine6` 的问题，可以暂时降级到 [v3.5.0.46-1](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.5.0.46-1)，参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

**Comment by Apple-QAQ** [comment]
> 应该是 `deepin-wine6` 的问题，可以暂时降级到 [v3.5.0.46-1](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.5.0.46-1)，参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

好的·，谢谢
