### ISSUE TITLE
“/opt/deepinwine/tools/run_v4.sh”: 没有那个文件或目录

### ISSUE THREAD

**Issue by russ1217** [vufa/deepin-wine-wechat-arch#205]
it seems that there is only run_v3.sh under “/opt/deepinwine/tools. Changing to run_v3.sh seems working.

**Comment by vufa** [comment]
fixed: https://github.com/vufa/deepin-wine-wechat-arch/commit/a4f600626777dd9c68a649949f4a74ac852cbf9c
