### ISSUE TITLE
libsasl2: file not found

### ISSUE THREAD

**Issue by Tianyue-Zhao** [vufa/deepin-wine-wechat-arch#207]
On running makepkg, the libsasl2 file in the source fails to download and gives 404 not found.
I checked and the file is indeed no longer available in the deepin repository.
I was able to get it working by downloading the libsasl2 file from here: http://ftp.debian.org/debian/pool/main/c/cyrus-sasl2/
![fail](https://user-images.githubusercontent.com/29241353/159112679-8c55adff-4bb8-48d1-a95d-ee12579bdb16.jpg)

**Comment by vufa** [comment]
updated: https://github.com/vufa/deepin-wine-wechat-arch/commit/21a84e6959c59a8674439c9f0ed224ba131cc99c
