### ISSUE TITLE
v3.6.0.18-1 中文字体显示为方框

### ISSUE THREAD

**Issue by lyjdwh** [vufa/deepin-wine-wechat-arch#208]
系统 manjaro，wechat 更新到v3.6.0.18-1 后，中文字体显示为方框，且readme里面解决中文字体显示为方框的方法没有效果。

**Comment by OrelEagle** [comment]
I had the same issue on Manjaro. Fixed by REMOVING `noto-fonts-sc` and `noto-fonts-cjk`. 

For displaying Chinese characters in other apps, I have installed `adobe-source-han-sans-cn-fonts`.

**Comment by lyjdwh** [comment]
感谢，中文字体的问题解决了。然后我把run.sh里面 `deepin-wine6-stable` 改成`deepin-wine5` 阴影边框也能消除了。不知道你是怎么消除 阴影边框 的问题的，还是说没遇到阴影边框呀 @OrelEagle

**Comment by CyrusYip** [comment]
系统：Arch Linux，字体：noto-fonts-cjk、adobe-source-han-sans-cn-fonts，用v3.6.0.18-1 也是方框。安装 v3.4.5.45-1 才能正常显示。

https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.4.5.45-1

**Comment by alienzj** [comment]
麻烦每次测试下再发布新的版本吧.

**Comment by vufa** [comment]
> > 系统：Arch Linux，字体：noto-fonts-cjk、adobe-source-han-sans-cn-fonts，用v3.6.0.18-1 也是方框。安装 v3.4.5.45-1 才能正常显示。
> > https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.4.5.45-1
> 
> [#204 (comment)](https://github.com/vufa/deepin-wine-wechat-arch/issues/204#issuecomment-1096062751)

参照 [README#中文字体显示为方框/显示模糊](https://github.com/vufa/deepin-wine-wechat-arch#%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E6%98%BE%E7%A4%BA%E4%B8%BA%E6%96%B9%E6%A1%86%E6%98%BE%E7%A4%BA%E6%A8%A1%E7%B3%8A)
