### ISSUE TITLE
聊天框点击发送文件按钮崩溃

### ISSUE THREAD

**Issue by sffred** [vufa/deepin-wine-wechat-arch#211]
问题版本：deepin-wine-wechat 3.6.0.18-1
似乎是 deepin-wine-helper 更新到 5.1.30_1-1 引起的

**Comment by hjwseu** [comment]
![image](https://user-images.githubusercontent.com/31691016/162694535-b4cace12-fae2-4cd5-8204-d8dc2d781c5f.png)
我也遇到了这个问题，而且拖拽文件发送的时候都会报“是一个空文件，无法发送，请重新选择。”

**Comment by sffred** [comment]
现似乎已修复，不排除是因为安装了noto-fonts-sc的原因
