### ISSUE TITLE
无法使用内置浏览器

### ISSUE THREAD

**Issue by sffred** [vufa/deepin-wine-wechat-arch#212]
deepin-wine-wechat 3.6.0.18-1
deepin-wine6-stable 6.0.0.19-1
点击链接后，内置浏览器窗口弹出，随即闪退

**Comment by baishui2004** [comment]
同样的问题，同样版本：
deepin-wine6-stable-amd64_6.0.0.19-1_amd64.deb
WeChatSetup-3.6.0.18.exe

**Comment by baishui2004** [comment]
已解决，yay -S noto-fonts-sc之后，内置浏览器可以打开，小程序也可以打开了


> 同样的问题，同样版本： deepin-wine6-stable-amd64_6.0.0.19-1_amd64.deb WeChatSetup-3.6.0.18.exe

**Comment by sffred** [comment]
@baishui2004 说的对
