### ISSUE TITLE
Cannot install AUR deepin-wine-wechat because of deepin-wine-helper error source 404

### ISSUE THREAD

**Issue by rbnxytt** [vufa/deepin-wine-wechat-arch#214]
==> ERROR: Failure while downloading https://community-store-packages.deepin.com/appstore/pool/appstore/d/deepin-wine-helper/deepin-wine-helper_5.1.30-1_i386.deb
    Aborting...

The source returns a 404.

**Comment by yswtrue** [comment]
一样的问题

**Comment by vufa** [comment]
The AUR package [deepin-wine-helper](https://aur.archlinux.org/packages/deepin-wine-helper) has been updated, reinstall to fix it.

**Comment by rbnxytt** [comment]
Thank you. I appreciate your efforts.
