### ISSUE TITLE
gnome无法粘贴图片

### ISSUE THREAD

**Issue by gqcdm** [vufa/deepin-wine-wechat-arch#219]
![image](https://user-images.githubusercontent.com/78142321/171608560-46183d0a-7ea8-4a30-8e16-cd6104b768aa.png)
![image](https://user-images.githubusercontent.com/78142321/171608632-bc5ea4b5-a97e-4465-8c08-830bf980a53f.png)
![image](https://user-images.githubusercontent.com/78142321/171608670-fd347d09-9fcc-4ada-b240-28ac0164db7d.png)
![image](https://user-images.githubusercontent.com/78142321/171608718-5e5de75b-a5e8-42c8-b28b-7efc10d11e35.png)

**Comment by vufa** [comment]
参照 https://github.com/vufa/deepin-wine-wechat-arch/issues/107#issuecomment-1134142004 试试

**Comment by gqcdm** [comment]
> 参照 [#107 (comment)](https://github.com/vufa/deepin-wine-wechat-arch/issues/107#issuecomment-1134142004) 试试

我不想更换wayland,于是我使用了上面安装其他包的方法发现不可行🤣
