### ISSUE TITLE
3.7.0小程序/朋友圈消息无法正常显示和使用等

### ISSUE THREAD

**Issue by EddyLee88** [vufa/deepin-wine-wechat-arch#220]
全新AUR安装了最新的3.7.0版本后,也安装了noto-fonts-sc,也把fake字体放到了指定目录内,小程序打开后一直显示在第一屏,但我鼠标点击相应的位置,title还会有变化,朋友圈消息也无法正常显示(Manjaro Gnome 21.2.6,之前3.6版本上述功能均正常)
![朋友圈](https://user-images.githubusercontent.com/22976892/171815634-4d8491d0-3d04-4fd9-99f8-c76c22f4f640.png)
![小程序](https://user-images.githubusercontent.com/22976892/171815647-76b388ce-cb5e-47a9-bea3-1a8c57100b13.gif)

**Comment by EddyLee88** [comment]
字体已经全部按照文档说明做好了,这个小程序也不是闪退,也不是方块,就是感觉有一层遮罩,应该很容易解决,但是无从下手

**Comment by faonecze** [comment]
强制结束这次小程序再打开小程序也这样吗?

**Comment by lxl6125** [comment]
同样的问题，一直显示加载的画面，但是实际上已经加载完成，小程序里的内容都可以点击，但是看不到具体内容
![2022-06-14_18-24-14](https://user-images.githubusercontent.com/21015800/173556162-bf754055-784f-4e3c-96c7-c824facdbbab.png)

**Comment by EddyLee88** [comment]
@vufa 请求支援...

**Comment by vufa** [comment]
不能复现这个问题，可以参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85) 降级到其他可用版本

**Comment by ArcanusNEO** [comment]
Arch Linux 5.18.12-zen
GNOME Shell 42.3.1
随时可以复现这个问题，存在时间挺久了。

https://user-images.githubusercontent.com/57259186/180360991-f39e8353-24f9-4b95-9451-5957341cf877.mp4

**Comment by vufa** [comment]
[v3.8.0.41-2](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.8.0.41-2)已经修复
