### ISSUE TITLE
为什么自从 3.5.0.46-1 之后的版本出现了更多的使用问题

### ISSUE THREAD

**Issue by listenerri** [vufa/deepin-wine-wechat-arch#221]
翻了下最近的 Issues，看起来从 3.5.0.46-2 版本（包含）开始好像就出现了更多影响使用的问题，而且相关 Issue 存留时间很长了已经，如果这是因为使用了 deepin-wine-6 的原因，请问为什么不换回 5 版本的呢？还是说这些问题只影响到了部分环境下的用户？

**Comment by vufa** [comment]
* deepin官方从 `com.qq.weixin.deepin 3.4.0.38deepin4` 开始，将安装包内自带的 `deepin-wine` 版本改为了 `deepin-wine6-stable`，但官方的 `deepin-wine` 版本较为混乱，`com.qq.weixin.deepin` 有时候会自带一份 `deepin-wine6-stable`，而不是使用 deepin 源中的 `deepin-wine6-stable`。为了和其他AUR包一致，`deepin-wine-wechat`使用 deepin源中的 `deepin-wine6-stable`，这导致可能出现原版不会出现的问题

* 也是从 `3.4.0.38deepin4` 开始，将运行脚本中的`deepin-wine6-stable` 替换为 `deepin-wine5` 会出现更多导致 WeChat 不能正常运行的问题，所以目前只能使用官方源中的 `deepin-wine6-stable` 运行 `deepin-wine-wechat`
