### ISSUE TITLE
wayland 下的异常

### ISSUE THREAD

**Issue by shenweijiekdel** [vufa/deepin-wine-wechat-arch#222]
1. wayland 窗口管理器下例如 sway, wayfire ，窗口被黑色窗口盖住了
2. wayland 下点击传输文件崩溃：
    wine invalid cast from 'GdkWaylandDisplay' to 'GdkX11Display

**Comment by abcfy2** [comment]
deepin wine的已知问题，准确来说，是整个wine都有的普遍问题

**Comment by moodyhunter** [comment]
加个 `GDK_BACKEND=x11` 貌似能解决问题

**Comment by shenweijiekdel** [comment]
已经使用 wine-for-wechat 解决，deepin-wine-wechat 有没有合并 wine-for-wechat 的 patch 的计划

**Comment by ystyle** [comment]
> 已经使用 wine-for-wechat 解决，deepin-wine-wechat 有没有合并 wine-for-wechat 的 patch 的计划

wine-for-wechat是什么 ？源里好像没有
