### ISSUE TITLE
占用磁盘空间持续增加

### ISSUE THREAD

**Issue by 1576378237** [vufa/deepin-wine-wechat-arch#225]
![image](https://user-images.githubusercontent.com/43315516/179443269-2fea390a-14b8-4cf2-a9b1-835ebdd88d78.png)
今天早上开机，磁盘空间被占满了，一查，.deepinwine占用了77G,清了重新运行，才几分钟，又占用4个G

**Comment by 1576378237** [comment]
![image](https://user-images.githubusercontent.com/43315516/179443747-2e7fc585-a8dc-4387-ae9e-8c9c5564927d.png)
这个 xweb文件夹，占用一直在增加！！！

**Comment by meteoryun** [comment]
我也是出现了相同了问题，只要运行微信，/xweb目录下就会不断的写.dump文件

**Comment by meteoryun** [comment]
> 我也是出现了相同了问题，只要运行微信，/xweb目录下就会不断的写.dump文件

@vufa

**Comment by 1576378237** [comment]
我现在临时的解决办法是通过定时任务每分钟都去去删除 ./xweb 下的文件， https://linux.zone/2252 @meteoryun

**Comment by meteoryun** [comment]
> 我现在临时的解决办法是通过定时任务每分钟都去去删除 ./xweb 下的文件， https://linux.zone/2252 @meteoryun

收到，谢谢。我准备采取降级处理。不知作者什么时候，一直让微信不停的在那里写感觉有点不安全，还是等作者升级之后看看

**Comment by meteoryun** [comment]
此此版本应该都有这个问题，可能他们/home划分空间较大还没发现，我是上午升级之后，接近下午6点就报磁盘空间不足了，写了70G数据在/xweb目录下面
@1576378237 @vufa

**Comment by vufa** [comment]
不能复现这个问题，可以暂时参照[用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)降级到其他可用版本

**Comment by meteoryun** [comment]
> 不能复现这个问题，可以暂时参照[用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)降级到其他可用版本

好的，谢谢。目前看出现问题的都是使用的 manjaro系统,@vufa

**Comment by blackeeper** [comment]
我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了

**Comment by meteoryun** [comment]
> 我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了

是创建一个同名的文件夹吗？文件名它是随机的.dump,一个200M左右，需要修改文件权限吗?@blackeeper

**Comment by blackeeper** [comment]
> > 我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了
> 
> 是创建一个同名的文件夹吗？文件名它是随机的.dump,一个200M左右，需要修改文件权限吗?@blackeeper

#删除这个目录
rm -rf ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports
#然后创建一个同名文件，这样目录就创建不了，也就不能写磁盘了
touch ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports

**Comment by meteoryun** [comment]
> > > 我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了
> > 
> > 
> > 是创建一个同名的文件夹吗？文件名它是随机的.dump,一个200M左右，需要修改文件权限吗?@blackeeper
> 
> #删除这个目录 rm -rf ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports #然后创建一个同名文件，这样目录就创建不了，也就不能写磁盘了 touch ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports

好的，谢谢，我刚试了可以，不知道有没有这样对微信。

**Comment by meteoryun** [comment]
> > > 我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了
> > 
> > 
> > 是创建一个同名的文件夹吗？文件名它是随机的.dump,一个200M左右，需要修改文件权限吗?@blackeeper
> 
> #删除这个目录 rm -rf ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports #然后创建一个同名文件，这样目录就创建不了，也就不能写磁盘了 touch ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports

好的，谢谢，我刚试了可以，目前看来暂未出现问题@blackeeper

**Comment by DerekRenew** [comment]
> > > 我也出现这个问题了，一天增加了200多G，直接把磁盘占满了，现在是把目录删掉，然后创建同名的文件，这样就写不了了
> > 
> > 
> > 是创建一个同名的文件夹吗？文件名它是随机的.dump,一个200M左右，需要修改文件权限吗?@blackeeper
> 
> #删除这个目录 rm -rf ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports #然后创建一个同名文件，这样目录就创建不了，也就不能写磁盘了 touch ~/.deepinwine/Deepin-WeChat/drive_c/users/blackeeper/Application Data/Tencent/WeChat/xweb/crash/Crashpad/reports

同manjaro系统，使用这个方法暂时解决了 @vufa

**Comment by vufa** [comment]
已经尝试添加了修复：https://github.com/vufa/deepin-wine-wechat-arch/commit/868856c9b8a860987a826a9c2df1ebbff5178ce1

**Comment by lu0se** [comment]
现在好像没这个问题了，尝试删除修改后使用了下
![a](https://user-images.githubusercontent.com/55630902/203226724-dc9fe7e7-b52f-4caf-9c40-e8aa809836da.png)

**Comment by olapEin** [comment]
依然存在此问题

![image](https://user-images.githubusercontent.com/73106094/223047725-6bbd27e4-26c9-45c5-bc19-78174f429a41.png)

版本:: 3.9.0.28-2  
操作系统:: Manjaro 22.0.4 Sikaris

**Comment by vufa** [comment]
[v3.9.0.28-3](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.9.0.28-3) 又把修复加回去了
