### ISSUE TITLE
会一直有wechatbrowser.e的进程生成，表情选择框无法正常弹出

### ISSUE THREAD

**Issue by DerekRenew** [vufa/deepin-wine-wechat-arch#231]
应用版本deepin-wine-wechat 3.7.5.23-1
操作系统：Manjaro Linux；构建 ID：rolling
Gnome版本：42.3
窗口系统：Wayland

当该进程生成时输入框会失去焦点，同时存在表情选择框无法正常弹出的现象

截图链接
https://s1.ax1x.com/2022/08/08/vMQNJ1.png

运行一段时间后能生成数十个该进程，不知道触发机制是什么
https://s1.ax1x.com/2022/08/08/vQ663t.png

**Comment by Baloneo** [comment]
https://github.com/vufa/deepin-wine-wechat-arch/issues/228#issuecomment-1203448264

**Comment by vufa** [comment]
与 https://github.com/vufa/deepin-wine-wechat-arch/issues/228 重复
