### ISSUE TITLE
md5sums 一个或多个文件没有通过有效性检查！

### ISSUE THREAD

**Issue by Delta-in-hub** [vufa/deepin-wine-wechat-arch#232]
==> 正在验证 source 文件，使用md5sums...
    com.qq.weixin.deepin_3.4.0.38deepin6_i386.deb ... 通过
    WeChatSetup-3.7.5.23.exe ... 失败
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... 通过
    libsasl2-2_2.1.27.1-1+dde_i386.deb ... 通过
    run.sh ... 通过
    reg.patch ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！

Linux MANJARO 5.15.59-1-MANJARO #1 SMP PREEMPT Wed Aug 3 11:20:04 UTC 2022 x86_64 GNU/Linux

使用`pikaur -S deepin-wine-wechat`

Package Details: deepin-wine-wechat 3.7.5.23-1

**Comment by Delta-in-hub** [comment]
从`https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe`下载的md5sum为`930141b82ed317250274c3aeb3750ae2`。
PKGBUILD里的对应md5sum为`86851da540577bb4e994cfc076a5776a`

**Comment by vufa** [comment]
已经更新：https://github.com/vufa/deepin-wine-wechat-arch/commit/868856c9b8a860987a826a9c2df1ebbff5178ce1
