### ISSUE TITLE
一个或多个文件没有通过有效性检查

### ISSUE THREAD

**Issue by Meow-2** [vufa/deepin-wine-wechat-arch#236]
WeChatSetUp.exe的md5又变了

https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
最新的 md5sum: 3d26396deef84239fdfabff06d7b3e35

PKGBUILD 中的 md5: 930141b82ed317250274c3aeb3750ae2

**Comment by vufa** [comment]
感谢提醒，已经更新：https://github.com/vufa/deepin-wine-wechat-arch/commit/63a73d8e58e2e6fc4efb0bfc0a97f5f5409ce6ba
