### ISSUE TITLE
 修改md5安装后无法启动

### ISSUE THREAD

**Issue by ddgip** [vufa/deepin-wine-wechat-arch#242]
yay 直接安装显示
==> ERROR: One or more files did not pass the validity check!
 -> error making: deepin-wine-wechat

直接git后修改PKGBUILD文件中的md5+值后成功安装但是无法启动，

手动运行 /opt/apps/com.qq.weixin.deepin/files/run.sh后的结果：
==> Deploying /home/ddgi/.deepinwine/Deepin-WeChat ...
==> Launching c:/Program Files/Tencent/WeChatSetup-3.7.6.29.exe ...
Don't use public dir
Run Deepin-WeChat 3.4.0.38deepin6 c:/Program Files/Tencent/WeChatSetup-3.7.6.29.exe
run Deepin-WeChat progress pid 

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:22796:24: not a number

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:23587:24: not a number

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:23593:24: not a number

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24188:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24194:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24200:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24206:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24212:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24218:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24224:20: Not a valid image

(zenity:80686): Gtk-WARNING **: 16:28:44.611: Theme parsing error: gtk.css:24230:20: Not a valid image
total 0
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 c: -> ../drive_c
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com1 -> /dev/ttyS0
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com10 -> /dev/ttyS9
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com11 -> /dev/ttyS10
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com12 -> /dev/ttyS11
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com13 -> /dev/ttyS12
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com14 -> /dev/ttyS13
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com15 -> /dev/ttyS14
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com16 -> /dev/ttyS15
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com17 -> /dev/ttyS16
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com18 -> /dev/ttyS17
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com19 -> /dev/ttyS18
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com2 -> /dev/ttyS1
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com20 -> /dev/ttyS19
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com21 -> /dev/ttyS20
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com22 -> /dev/ttyS21
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com23 -> /dev/ttyS22
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com24 -> /dev/ttyS23
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com25 -> /dev/ttyS24
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com26 -> /dev/ttyS25
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com27 -> /dev/ttyS26
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com28 -> /dev/ttyS27
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com29 -> /dev/ttyS28
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com3 -> /dev/ttyS2
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com30 -> /dev/ttyS29
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com31 -> /dev/ttyS30
lrwxrwxrwx 1 ddgi ddgi 11 Sep  5 16:28 com32 -> /dev/ttyS31
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com4 -> /dev/ttyS3
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com5 -> /dev/ttyS4
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com6 -> /dev/ttyS5
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com7 -> /dev/ttyS6
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com8 -> /dev/ttyS7
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 com9 -> /dev/ttyS8
lrwxrwxrwx 1 ddgi ddgi  8 Sep  5 16:28 d:: -> /dev/sr0
lrwxrwxrwx 1 ddgi ddgi 10 Sep  5 16:28 y: -> /home/ddgi
lrwxrwxrwx 1 ddgi ddgi  1 Sep  5 16:28 z: -> /
CallApp Deepin-WeChat arg count 1: c:/Program Files/Tencent/WeChatSetup-3.7.6.29.exe
Don't use public dir
Mon Sep  5 04:28:45 PM JST 2022:kill Deepin-WeChat block
Mon Sep  5 04:28:45 PM JST 2022:tag bottle: /home/ddgi/.deepinwine/Deepin-WeChat
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
Mon Sep  5 04:28:45 PM JST 2022:active bottles: 
Mon Sep  5 04:28:45 PM JST 2022:try to kill /home/ddgi/.deepinwine/Deepin-WeChat
/opt/deepinwine/tools/kill.sh: line 66: /proc/80869/environ: No such file or directory
cat: /proc/80869/maps: No such file or directory
cat: /proc/80869/cmdline: No such file or directory
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
cat: /proc/80869/maps: No such file or directory
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
cat: /proc/76952/maps: Permission denied
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
cat: /proc/76952/maps: Permission denied
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
cat: /proc/80894/maps: No such file or directory
cat: /proc/80894/cmdline: No such file or directory
xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
cat: /proc/80894/maps: No such file or directory
ddgi       81101   80720  0 16:28 pts/0    00:00:00 grep -E ddgi.*exe.*<defunct>
/home/ddgi/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent
==> Creating /home/ddgi/.deepinwine/Deepin-WeChat/PACKAGE_VERSION ...
ddgi@ ~  -> wine version: 6.0
wine: Call from 7B03A8AF to unimplemented function user32.dll.CreateDialogParamW, aborting
wine: Unimplemented function user32.dll.CreateDialogParamW called at address 7B03A8AF (thread 002c), starting debugger...
wine: Call from 7B03A8AF to unimplemented function user32.dll.GetProcessWindowStation, aborting

**Comment by vufa** [comment]
已经更新，安装最新版试试

**Comment by ddgip** [comment]
解决了，是之前安装的deepin-wine6-stable的问题，重新安装deepin-wine6-stable后再次安装成功运行了
