### ISSUE TITLE
无法安装，提示md5sums

### ISSUE THREAD

**Issue by fastLazy** [vufa/deepin-wine-wechat-arch#244]
==> 正在创建软件包：deepin-wine-wechat 3.7.6.29-1 (2022年09月06日 星期二 09时12分28秒)
==> 正在检查运行时依赖关系...
==> 正在检查编译时依赖关系
==> 获取源代码...
  -> 找到 com.qq.weixin.deepin_3.4.0.38deepin6_i386.deb
  -> 找到 WeChatSetup-3.7.6.29.exe
  -> 找到 libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb
  -> 找到 libsasl2-2_2.1.27.1-1+dde_i386.deb
  -> 找到 run.sh
  -> 找到 reg.patch
==> 正在验证 source 文件，使用md5sums...
    com.qq.weixin.deepin_3.4.0.38deepin6_i386.deb ... 通过
    WeChatSetup-3.7.6.29.exe ... 失败
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... 通过
    libsasl2-2_2.1.27.1-1+dde_i386.deb ... 通过
    run.sh ... 通过
    reg.patch ... 通过
==> 错误： 一个或多个文件没有通过有效性检查！
 -> 生成时出错: deepin-wine-wechat

**Comment by fastLazy** [comment]
/.cache/yay/deepin-wine-wechat/PKGBUILD:行50: patch：未找到命令

**Comment by Solo8World** [comment]
可以跳过md5检查：
如果是arch的话，用 `yay -S  --m-arg --skipchecksums deepin-wine-wechat`

**Comment by vufa** [comment]
已经更新：https://github.com/vufa/deepin-wine-wechat-arch/commit/37f1d678db5c7fffa5baf0a953ad78454bad999e
