### ISSUE TITLE
降级安装后，每次打开都是自动重装wechat程序。

### ISSUE THREAD

**Issue by vvlaw** [vufa/deepin-wine-wechat-arch#249]
应该是 `deepin-wine6` 的问题，可以暂时降级到 [v3.5.0.46-1](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.5.0.46-1)，参照 [用安装包安装](https://github.com/vufa/deepin-wine-wechat-arch#%E7%94%A8%E5%AE%89%E8%A3%85%E5%8C%85%E5%AE%89%E8%A3%85)

_Originally posted by @vufa in https://github.com/vufa/deepin-wine-wechat-arch/issues/200#issuecomment-1042913882_

用yay安装后可以正常打开使用，但是还是有阴影，想用版本切换，
vvlaw@archlinux  ~  /opt/apps/com.qq.weixin.deepin/files/run.sh -d
```
Don't use public dir
Run Deepin-WeChat 3.2.1.154deepin14 c:/Program Files/Tencent/WeChat/WeChat.exe -d
Invalid option: -d
Use -h|--help to get help
```

所以想用本地安装包安装[v3.5.0.46-1] ，但是安装后每次打开都要会自动重装wechat

**Comment by vufa** [comment]
参照[最新的run.sh](https://github.com/vufa/deepin-wine-wechat-arch/blob/action/run.sh)，对 `/opt/apps/com.qq.weixin.deepin/files/run.sh`修改试试：
```diff
Run()
{
    if [ -z "$DISABLE_ATTACH_FILE_DIALOG" ];then
        export ATTACH_FILE_DIALOG=1
    fi

    if [ -n "$EXEC_PATH" ];then
        if [ ! -f "$WINEPREFIX/reinstalled" ];then
            # run installer
            env WINEDLLOVERRIDES="winemenubuilder.exe=d" $START_SHELL_PATH $BOTTLENAME $APPVER "$WECHAT_INSTALLER_PATH" "$@"
            touch $WINEPREFIX/reinstalled
+            cat /opt/apps/$DEB_PACKAGE_NAME/files/files.md5sum > $WINEPREFIX/PACKAGE_VERSION
+            exit 0
        else
            if [ -z "${EXEC_PATH##*.lnk*}" ];then
                $START_SHELL_PATH $BOTTLENAME $APPVER "C:/windows/command/start.exe" "/Unix" "$EXEC_PATH" "$@"
            else
                $START_SHELL_PATH $BOTTLENAME $APPVER "$EXEC_PATH" "$@"
            fi
        fi
    else
        $START_SHELL_PATH $BOTTLENAME $APPVER "uninstaller.exe" "$@"
    fi
}
```

**Comment by vvlaw** [comment]
改了最新的run.sh还是不行哦：（

**Comment by vvlaw** [comment]
降级安装还是不成功，显示
` vvlaw@archlinux  ~  /opt/apps/com.qq.weixin.deepin/files/run.sh winecfg
Wine cannot find the ncurses library (libncurses.so.6).
 vvlaw@archlinux  ~    `

是不是libncurses.so.6的问题？

第一次打开没反应，第二次打开就进行安装。。。

**Comment by vvlaw** [comment]
安装最新版的打开winecfg提示不一样

` vvlaw@archlinux  ~  /opt/apps/com.qq.weixin.deepin/files/run.sh winecfg
==> Launching winecfg with deepin-wine6-stable in /home/vvlaw/.deepinwine/Deepin-WeChat ...
/usr/bin/deepin-wine6-stable: line 46: arch: command not found
/usr/bin/deepin-wine6-stable: line 48: [: too many arguments`

**Comment by vvlaw** [comment]
看样子是deepin-wine-helper的`/opt/deepinwine/tools/run_v4.sh`文件里APPVER有时不能成功写入：
```
echo "$APPVER" > "$WINEPREFIX/PACKAGE_VERSION"
```
导致后续在UpdateApp时做的版本检查没有通过，触发了删除的逻辑：
```
if [ -f "$WINEPREFIX/PACKAGE_VERSION" ] && [ "$(cat "$WINEPREFIX/PACKAGE_VERSION")" = "$APPVER" ]; then
  return
fi
...
case $BOTTLENAME in
        "Deepin-Intelligent" | "Deepin-QQ" | "Deepin-TIM" | "Deepin-WeChat" | "Deepin-WXWork" | "Deepin-Dding")
            rm -rf "$WINEPREFIX"
            DeployApp
            return
            ;;
    esac
```



所以在安装后（指存在`c:/Program Files/Tencent/WeChat/WeChat.exe`），需要检查一下`$HOME/.deepinwine/Deepin-WeChat/PACKAGE_VERSION`文件是否存在，如果不存在那么可以试试这个：
```
cat /opt/apps/com.qq.weixin.deepin/files/files.md5sum > $HOME/.deepinwine/Deepin-WeChat/PACKAGE_VERSION
```

_Originally posted by @TangliziGit in https://github.com/vufa/deepin-wine-wechat-arch/issues/213#issuecomment-1090471461_

**Comment by vvlaw** [comment]
cat /opt/apps/com.qq.weixin.deepin/files/files.md5sum > $HOME/.deepinwine/Deepin-WeChat/PACKAGE_VERSION

用TangliziGit提供的这条命令解决了。
[https://github.com/vufa/deepin-wine-wechat-arch/issues/213#issuecomment-1090471461](url)

**Comment by vvlaw** [comment]
不过现在唤醒不了后台了。。。

` vvlaw@archlinux  ~  /opt/deepinwine/tools/sendkeys.sh w wechat 4
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
cat: /proc/61688/maps: No such file or directory
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
cat: /proc/61688/maps: No such file or directory
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
grep: warning: stray \ before /
send to 60314=/home/vvlaw/.deepinwine/Deepin-WeChat by /usr/lib/i386-linux-gnu/deepin-wine5/wine
Wine cannot find the ncurses library (libncurses.so.6).
key down: (ctrl+alt+W), 3, 0
key up: (ctrl+alt+W), 3, 0`

**Comment by vufa** [comment]
唤醒窗口参照 [唤出已运行的 WeChat 窗口](https://github.com/vufa/deepin-wine-wechat-arch#%E5%94%A4%E5%87%BA%E5%B7%B2%E8%BF%90%E8%A1%8C%E7%9A%84-wechat-%E7%AA%97%E5%8F%A3)
