### ISSUE TITLE
expat-2.4.8-1

### ISSUE THREAD

**Issue by IT-Tagore** [vufa/deepin-wine-wechat-arch#250]
在arch设备上该依赖阻碍了正常的系统更新,

**Comment by glide-the** [comment]
> 



> 同样遇到了问题，我强制删除了相关依赖后，系统更新成功，deepin-wine5相关应用无法启动
> 
> 显示如下报错
> 
> ```
> ~ >>> /opt/apps/com.qq.weixin.deepin/files/run.sh                          
> ==> Launching  c:/Program Files/Tencent/WeChat/WeChat.exe ...
> Don't use public dir
> Run Deepin-WeChat 3.4.0.38deepin6 c:/Program Files/Tencent/WeChat/WeChat.exe
> run Deepin-WeChat progress pid 
> Gtk-Message: 20:26:21.548: Failed to load module "appmenu-gtk-module"
> 总计 0
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 c: -> ../drive_c
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com1 -> /dev/ttyS0
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com10 -> /dev/ttyS9
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com11 -> /dev/ttyS10
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com12 -> /dev/ttyS11
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com13 -> /dev/ttyS12
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com14 -> /dev/ttyS13
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com15 -> /dev/ttyS14
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com16 -> /dev/ttyS15
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com17 -> /dev/ttyS16
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com18 -> /dev/ttyS17
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com19 -> /dev/ttyS18
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com2 -> /dev/ttyS1
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com20 -> /dev/ttyS19
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com21 -> /dev/ttyS20
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com22 -> /dev/ttyS21
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com23 -> /dev/ttyS22
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com24 -> /dev/ttyS23
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com25 -> /dev/ttyS24
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com26 -> /dev/ttyS25
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com27 -> /dev/ttyS26
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com28 -> /dev/ttyS27
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com29 -> /dev/ttyS28
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com3 -> /dev/ttyS2
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com30 -> /dev/ttyS29
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com31 -> /dev/ttyS30
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 com32 -> /dev/ttyS31
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com4 -> /dev/ttyS3
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com5 -> /dev/ttyS4
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com6 -> /dev/ttyS5
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com7 -> /dev/ttyS6
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com8 -> /dev/ttyS7
> lrwxrwxrwx 1 dmeck dmeck 10 10月 3日 20:26 com9 -> /dev/ttyS8
> lrwxrwxrwx 1 dmeck dmeck  8  9月13日 09:57 d:: -> /dev/sr0
> lrwxrwxrwx 1 dmeck dmeck 11 10月 3日 20:26 y: -> /home/dmeck
> lrwxrwxrwx 1 dmeck dmeck  1 10月 3日 20:26 z: -> /
> CallApp Deepin-WeChat arg count 1: c:/Program Files/Tencent/WeChat/WeChat.exe
> Don't use public dir
> 2022年 10月 03日 星期一 20:26:21 CST:kill Deepin-WeChat block
> 2022年 10月 03日 星期一 20:26:21 CST:tag bottle: /media/target/home/dmeck/.deepinwine/Deepin-WeChat
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> 2022年 10月 03日 星期一 20:26:21 CST:active bottles: 
> 2022年 10月 03日 星期一 20:26:21 CST:try to kill /media/target/home/dmeck/.deepinwine/Deepin-WeChat
> 2022年 10月 03日 星期一 20:26:21 CST:kill /media/target/home/dmeck/.deepinwine/Deepin-WeChat by /opt/deepin-wine6-stable/bin/wineserver.real
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> xargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> cat: /proc/7386/maps: 没有那个文件或目录grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> cat: /proc/7386/cmdlinexargs: warning: options --max-lines and --replace/-I/-i are mutually exclusive, ignoring previous --max-lines value
> : 没有那个文件或目录grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> grep: 警告：/ 前有多余的 \
> cat: /proc/7386/maps: 没有那个文件或目录grep: 警告：/ 前有多余的 \
> dmeck       7669    7135  0 20:26 pts/1    00:00:00 grep -E dmeck.*exe.*<defunct>
> /home/dmeck/.deepinwine/Deepin-WeChat/drive_c/Program Files/Tencent/WeChat
> /usr/bin/deepin-wine6-stable:行46: arch：未找到命令                         
> /usr/bin/deepin-wine6-stable: 第 48 行：[: 参数太多~ >>> wine version: 6.0                                                    
> wine: Call from 7B03A8AF to unimplemented function shell32.dll.SHGetFolderPathW, aborting
> wine: Unimplemented function shell32.dll.SHGetFolderPathW called at address 7B03A8AF (thread 002c), starting debugger...
> wine: Call from 7B03A8AF to unimplemented function shell32.dll.SHGetDesktopFolder, aborting
> wine: Unimplemented function shell32.dll.SHGetDesktopFolder called at address 7B03A8AF (thread 00c0), starting debugger...
> ```

问题已经解决，上游系统更新强制合并了pacman.conf文件，导致Multilib仓库被注释，打开/etc/pacman.conf把注释去掉然后执行如下命令就可以了

```
sudo pacman -Syuu
```
