### ISSUE TITLE
能否更换默认的微信图标？

### ISSUE THREAD

**Issue by 15805383399** [vufa/deepin-wine-wechat-arch#257]
deepin-wine-wechat 自带的微信图标看着很别扭, 我自己参照我微信官方的svg图标修改了，看着更加舒服了，希望能更换。
* 自带图标：
![图片](https://user-images.githubusercontent.com/76238405/200777128-ed3deb84-09c1-4ea5-b327-8494004ceaf7.png)

* 微信官方图标
![图片](https://user-images.githubusercontent.com/76238405/200777337-d72aa43a-881c-4b67-974a-90bcc041155c.png)

* 修改后的图标
![图片](https://user-images.githubusercontent.com/76238405/200777449-0bb49ab9-6313-4329-bb84-f3b76fe51e80.png)

修改后图标的 png 文件 (512 * 512)：
![wechat](https://user-images.githubusercontent.com/76238405/200779715-546612c4-a150-4833-bef8-ae875e809022.png)

**Comment by vufa** [comment]
第一张图并不是 deepin包 `com.qq.weixin.deepin` 中的自带图标，应该是[`papirus-icon-theme`中的图标](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2452)，也许你可以自定义图标包或在桌面环境设置中调整 `com.qq.weixin.deepin` 的图标
