### ISSUE TITLE
ERROR: One or more files did not pass the validity check!

### ISSUE THREAD

**Issue by ljf-98** [vufa/deepin-wine-wechat-arch#258]
再次出现了此报错：
==> Validating source files with md5sums...
    com.qq.weixin.deepin_3.4.0.38deepin6_i386.deb ... Passed
    WeChatSetup-3.7.6.44.exe ... FAILED
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... Passed
    libsasl2-2_2.1.27.1-1+dde_i386.deb ... Passed
    run.sh ... Passed
    reg.patch ... Passed
==> ERROR: One or more files did not pass the validity check!

**Comment by XGZepto** [comment]
你本地計算一下 WeChatSetup 的 md5sum，然後去 ~/.cache/yay/deepin-wine-wechat/PKGBUILD 替換，之後 makepkg 安裝就好

**Comment by vufa** [comment]
感谢提醒，已经更新
