### ISSUE TITLE
can't install deepin-wine6-stable

### ISSUE THREAD

**Issue by Windforce17** [vufa/deepin-wine-wechat-arch#259]
```sh
 -> Could not find all required packages:
  deepin-udis86 (Wanted by: deepin-wine6-stable)
```
是我的源的问题吗？

**Comment by HXMing** [comment]
我也遇到了同样的问题，你解决了吗？

**Comment by HXMing** [comment]
> 

我也遇到了同样的问题，你解决了吗？

**Comment by linsyking** [comment]
手动安装一下udis86-git即可

**Comment by Windforce17** [comment]
新版已修复了好像。

**Comment by linhandev** [comment]
感觉并没修复，我今天新做的arch安装说找不到 deepin-wine6-stable，yay -S deepin-wine6-stable 说找不到 deepin-udis86。这个包目前aur上404。装udis86-git没解决问题，跟着[这个issue](https://github.com/vufa/deepin-wine-tim-arch/issues/119#issuecomment-913084248)装了deepin-udis86之后装上了
