### ISSUE TITLE
[Suggest 建议] 优化快捷键脚本 Improve shortcut script

### ISSUE THREAD

**Issue by bryango** [vufa/deepin-wine-wechat-arch#262]
README 建议的快捷键不知为何超级慢：
This is super slow on my laptop:

https://github.com/vufa/deepin-wine-wechat-arch/blob/37f1d678db5c7fffa5baf0a953ad78454bad999e/README.md?plain=1#L239-L249

... and I don't know why. For that, I wrote [a small script](https://gist.github.com/bryango/560c59bb095df20e11dadb659dd8faa0) using `xdotool` (based on other people's suggestions) which works fast for me. Basically, it's just:

参考网上别人的操作我用 `xdotool` 写了[一个小脚本](https://gist.github.com/bryango/560c59bb095df20e11dadb659dd8faa0)，主要也就是一句话：

```bash
KEYS=ctrl+alt+w
WMCLASS_WINE="Wine|.exe"

for pid in $(pgrep explorer.exe); do
    xdotool \
        search \
            --pid "$pid" \
            --class "$WMCLASS_WINE" \
        key \
            --clearmodifiers "$KEYS" \
    && exit 0
    # ... `--clearmodifiers` improves continuous toggling
done
```

这个几乎是瞬间呼出微信，供参考。

**Comment by vufa** [comment]
已经参照 @metahy 的建议添加了命令`-w`，参照[README](https://github.com/vufa/deepin-wine-wechat-arch#%E5%94%A4%E5%87%BA%E5%B7%B2%E8%BF%90%E8%A1%8C%E7%9A%84wechat%E7%AA%97%E5%8F%A3)试试:
```bash
/opt/apps/com.qq.weixin.deepin/files/run.sh -w
```
