### ISSUE TITLE
视频号、看一看无法使用，内置浏览器有问题

### ISSUE THREAD

**Issue by xiaoyin199** [vufa/deepin-wine-wechat-arch#265]
3.8以前版本，是视频不能播放，内置浏览器不能使用；
3.8升级后视频可以播放了，但是一蹦一蹦的有点观看上的问题，不过能忍受；
但是内置浏览器不能用，挺尴尬！是大家都不能用，还是……

**Comment by LiTEiTStudio** [comment]
放心，咱都用不了

**Comment by ADSR1042** [comment]
小程序内调用内置webview也无法使用

**Comment by tinyweet** [comment]
spark 的版本可以看视频号, 但是显示又有各种问题

**Comment by vufa** [comment]
[v3.9.0.28-2](https://github.com/vufa/deepin-wine-wechat-arch/releases/tag/v3.9.0.28-2) 修复了内置浏览器

**Comment by guma17** [comment]
v3.9.0.28-3, 内置浏览器还是有问题，一片空白 @vufa
