### ISSUE TITLE
WeChatSetup.exe校验失败

### ISSUE THREAD

**Issue by AI1379** [vufa/deepin-wine-wechat-arch#268]
微信版本更新后使用yay安装提示校验失败
貌似修改pkgbuild的第二个md5sums然后makepkg -si就好了

**Comment by bloaryth** [comment]
==> Validating source files with md5sums...
    com.qq.weixin.deepin_3.4.0.38deepin6_i386.deb ... Passed
    WeChatSetup-3.8.0.41.exe ... FAILED
    libldap-2.4-2_2.4.47+dfsg.4-1+eagle_i386.deb ... Passed
    libsasl2-2_2.1.27.1-1+dde_i386.deb ... Passed
    run.sh ... Passed
    reg.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: deepin-wine-wechat 
         context: exit status 1

**Comment by Kingtous** [comment]
可以在yay的时候添加`--mflags --skipinteg`，可以跳过md5检测。

**Comment by AI1379** [comment]
> 可以在yay的时候添加`--mflags --skipinteg`，可以跳过md5检测。

这看起来是一个好办法

说起来有没有可能用一些方式随着微信的版本更新自动更新这个md5sums啊

比如说用一个github action检测微信官网的版本号然后自动更新pkgbuild

不过这只是一个个人的想法

**Comment by vufa** [comment]
感谢提醒，已经更新
