### ISSUE TITLE
Missing dependency deepin-udis86 on AUR

### ISSUE THREAD

**Issue by campagnani** [vufa/deepin-wine-wechat-arch#269]
As you can see [don't have deepin-udis86 on AUR today.](https://aur.archlinux.org/packages?O=0&K=deepin-udis86)

So when I use a AUR Helper, like paru:

```
paru -S deepin-wine-wechat
```

I recive the following error:

```
error: could not find all required packages:
    deepin-udis86 (wanted by: deepin-wine-wechat -> deepin-wine6-stable)
```

I solve it doing
```
git clone https://github.com/JohnMasoner/deepin-udis86.git
cd deepin-udis86
makepkg -si
```
before execute paru installation.

But it's possible put deepin-udis86 on AUR to AUR Helper's work's without intervention?

Thank's!

**Comment by vufa** [comment]
> https://bbs.archlinuxcn.org/viewtopic.php?id=13064

`deepin-udis86` has been replaced by [`lib32-udis86-git`](https://aur.archlinux.org/packages/lib32-udis86-git), you can manually install it to solve this problem:
```bash
# import gpg key according to PKGBUILD
curl https://github.com/canihavesomecoffee.gpg | gpg --import
# install lib32-udis86-git
yay -S lib32-udis86-git
```
