### ISSUE TITLE
下载安装微信3.9版，启动后wine提示“程序错误”

### ISSUE THREAD

**Issue by raynhard11** [vufa/deepin-wine-wechat-arch#274]
安装方法
$ git clone https://aur.archlinux.org/deepin-wine-wechat.git
$ cd deepin-wine-wechat
缺少aur才有的依赖
$ sudo pamac install deepin-wine6-stable deepin-wine-helper wqy-microhei lib32-openal lib32-mpg123
依赖安装好后，执行安装，跳过md5检查
$ makepkg -si --skipchecksums
启动“微信”，按提示一系列的缺省安装步骤后报错
![image](https://user-images.githubusercontent.com/125555314/219338489-28e33a94-321e-49b3-b923-29664a7a0be3.png)
是不是微信3.9的问题？哪里能下载到指定版本的WeChatSetup.exe安装包呢？

**Comment by chaofanx** [comment]
[release](https://github.com/vufa/deepin-wine-wechat-arch/releases)里面下载历史版本然后 `pacman -U xxx` 安装

**Comment by SamuelW9527** [comment]
微信安装目录里面的mmmojo.dll跟mmmojo_x64.dll更换成3.8.x版本的

**Comment by vufa** [comment]
感谢 @SamuelW9527 ,已经修复：https://github.com/vufa/deepin-wine-wechat-arch/commit/395cb81de45f4408e6ea8155b44b1dc11bb7cc43 ，由于AUR对文件体积的限制，暂时未上传到AUR
