### ISSUE TITLE
不断生成Crash日志文件占用磁盘空间

### ISSUE THREAD

**Issue by ChinaNuke** [vufa/deepin-wine-wechat-arch#275]
微信运行时会一直生成Crash reports，直到把磁盘空间占满。

![图片](https://user-images.githubusercontent.com/17084130/221553046-9690bd16-5afc-4a41-8b6c-40c3199b6eab.png)

尝试了通过 `yay -Rns deepin-wine-wechat` 卸载然后重新安装，还是会出现一样的问题。

**Comment by vufa** [comment]
参照 https://github.com/vufa/deepin-wine-wechat-arch/issues/225
