### ISSUE TITLE
安装后有黑边

### ISSUE THREAD

**Issue by wwangbzh** [vufa/deepin-wine-wechat-arch#33]
这个系列版本安装后一直有黑边
现在能否将深度 版2.6.8版本移植过来，就行TIM一样 deepin.com.qq.office 2.0.0deepin4-2 移植一样？
感觉深度的版本bug少不少，那样可能只是deb包 转变为pkg包相信难度也少不小？

**Comment by wwangbzh** [comment]
之前两个版本都有，但是现在深度版的没了

**Comment by countstarlight** [comment]
深度版2.6.8是指什么？

**Comment by wwangbzh** [comment]
深度 版微信 版本号V2.6.8  ， [https://mirrors.huaweicloud.com/deepin/pool/non-free/d/deepin.com.wechat/]

自己通过debtap工具转的包安装 闪退。

**Comment by wwangbzh** [comment]
安装 gnome-settings-daemon后+自启动 也不行，有进程 但不能正常启动

**Comment by blackstorm** [comment]
同样有黑边

**Comment by countstarlight** [comment]
参照[#消除阴影边框](https://github.com/countstarlight/deepin-wine-wechat-arch#%E6%B6%88%E9%99%A4%E9%98%B4%E5%BD%B1%E8%BE%B9%E6%A1%86)试试
