### ISSUE TITLE
删除注册表这三个字段可以去低版本更新提示

### ISSUE THREAD

**Issue by deepkolos** [vufa/deepin-wine-wechat-arch#41]
直接那deepin包的微信替换已安装的，然后修改注册表，启用deepin-wine, 就可以比现在更好的使用体验

https://mirrors.aliyun.com/deepin/pool/non-free/d/deepin.com.wechat/deepin.com.wechat_2.6.8.65deepin0_i386.deb

![wx](https://user-images.githubusercontent.com/12824616/71674628-ac864580-2db6-11ea-94c5-433b154fae84.png)

![图片](https://user-images.githubusercontent.com/12824616/71674715-f3743b00-2db6-11ea-9e82-d783dd7717c7.png)

**Comment by countstarlight** [comment]
注册表中这个值 `Version` 在微信运行时会自动写入和更新，在打包的时候删掉这个值可能是无效的。现在是屏蔽 `wechatupdate.exe` 来防止更新，但在找不到 `wechatupdate.exe` 的时候微信可能不能运行
