### ISSUE TITLE
小程序中字体全部显示为方框

### ISSUE THREAD

**Issue by jimorsm** [vufa/deepin-wine-wechat-arch#53]
系统：Manjaro 20.0 rc3 Gnome
wine:   5.5
版本：2.9.0.112-1
![image](https://user-images.githubusercontent.com/3843791/80169992-84e31380-8619-11ea-8062-c40a9d1472d6.png)
![image](https://user-images.githubusercontent.com/3843791/80170042-9f1cf180-8619-11ea-80f6-fcf47c6425d0.png)

**Comment by bruiselee** [comment]
WINPREFIX=容器路径 winetrick cjkfonts

**Comment by vufa** [comment]
参照 [中文字体显示为方框/显示模糊](https://github.com/vufa/deepin-wine-wechat-arch#%E4%B8%AD%E6%96%87%E5%AD%97%E4%BD%93%E6%98%BE%E7%A4%BA%E4%B8%BA%E6%96%B9%E6%A1%86%E6%98%BE%E7%A4%BA%E6%A8%A1%E7%B3%8A)
