### ISSUE TITLE
扫码登录以后程序自动关闭

### ISSUE THREAD

**Issue by vince923** [vufa/deepin-wine-wechat-arch#55]
请问,扫码登录以后程序自动关闭怎么破?谢谢
`libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
X Error of failed request:  GLXBadContext
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  6 (X_GLXIsDirect)
  Serial number of failed request:  474
  Current serial number in output stream:  473`

**Comment by yech1990** [comment]
This might help:

```bash
sudo pacman -S  lib32-nvidia-utils
```
