### ISSUE TITLE
无法使用小程序

### ISSUE THREAD

**Issue by Zolyn** [vufa/deepin-wine-wechat-arch#60]
系统: Arch Linux
桌面环境: Deepin + Kwin
版本: 2.9.0-123-1
侧边栏没有小程序图标，打开小程序显示不支持当前系统版本

**Comment by countstarlight** [comment]
切换到 `deepin-wine` 后，注册表中的系统版本会被改为 `Windows XP`，微信在`Windows XP` 上会停用小程序功能；最新版的 `wine 5.9` 也不支持小程序，会崩溃

**Comment by leo-mao** [comment]
感觉更像是Feature Request

**Comment by 1900011604** [comment]
但是我改成Win 7也不行啊

会显示这个
https://szsupport.weixin.qq.com/cgi-bin/mmsupport-bin/newreadtemplate?t=upgrade_common&pass_ticket=BUdZMH%2Fm76IHYvF1q9WSiBdutaetgkf625jXQV3euPEPyCNut3YuJY5QjP9DYfbc&wechat_real_lang=zh_CN

**Comment by 1900011604** [comment]
> 切换到 `deepin-wine` 后，注册表中的系统版本会被改为 `Windows XP`，微信在`Windows XP` 上会停用小程序功能；最新版的 `wine 5.9` 也不支持小程序，会崩溃

那么应该怎么解决呢

**Comment by 1900011604** [comment]
deepin-wine5不支持小程序，只会显示白屏

**Comment by abolast** [comment]
可能和微信浏览器内核有关，不止不能打开小程序，还不能打开公众号文章，对于公众号文章，我使用系统浏览器Firefox打开

**Comment by vufa** [comment]
v3.5.0.46-2 修复了小程序和查看公众号文章功能
