### ISSUE TITLE
微信公众号详情页不可用，打开为白板

### ISSUE THREAD

**Issue by panpeng0014** [vufa/deepin-wine-wechat-arch#83]
系统: Manjaro Xfce
桌面环境: xfce
版本: 3.0.0
无法查看公众号的详情页面

**Comment by countstarlight** [comment]
这个暂时没办法解决，可以点击窗口上方的 `用默认浏览器打开`

**Comment by chengs2035** [comment]
我显示是黑板。

**Comment by Brannua** [comment]
我也是，manjaro 20.2.1 kde 公众号的文章在微信打开是纯黑，啥也没有

**Comment by JoveYu** [comment]
winecfg  修改windows版本为XP   可以解决浏览器使用问题    不过会禁用小程序

**Comment by vufa** [comment]
v3.5.0.46-2 修复了小程序和查看公众号文章功能
