### ISSUE TITLE
无法显示小程序窗口内容

### ISSUE THREAD

**Issue by SamLukeYes** [vufa/deepin-wine-wechat-arch#89]
测试环境：Manjaro GNOME (unstable branch), 未切换到 deepin-wine

启动小程序后一段时间，启动动画会卡住。此时按下 Super 键，发现小程序已经加载完毕，在多任务视图中能正常显示其界面。再点击小程序界面，小程序窗口立即白屏。多次尝试后发现，只有在多任务视图中可以正常显示小程序界面。一旦切换至正常界面，小程序就会白屏，无法使用。

**Comment by SamLukeYes** [comment]
开了虚拟桌面后似乎就正常了

**Comment by vufa** [comment]
v3.5.0.46-2 修复了小程序和查看公众号文章功能
